import { LevelConfig } from './types';

export const LEVELS_111_150: LevelConfig[] = [
  {
    id: 111,
    title: 'Level 111',
    gridSize: 5,
    initialTiles: [
      { id: 'l111-tile-1', color: 'red', number: 3 },
      { id: 'l111-tile-2', color: 'grey' },
      { id: 'l111-tile-3', color: 'grey' },
      { id: 'l111-tile-4', color: 'red' },
      { id: 'l111-tile-5', color: 'grey' },
      { id: 'l111-tile-6', color: 'red' },
      { id: 'l111-tile-7', color: 'cyan', isFrozen: true },
      { id: 'l111-tile-8', color: 'grey' },
      { id: 'l111-tile-9', color: 'grey' },
      { id: 'l111-tile-10', color: 'grey' },
      { id: 'l111-tile-11', color: 'grey' },
      { id: 'l111-tile-12', color: 'grey' },
      { id: 'l111-tile-13', color: 'grey' },
      { id: 'l111-tile-14', color: 'grey' },
      { id: 'l111-tile-15', color: 'blue' },
      { id: 'l111-tile-16', color: 'grey' },
      { id: 'l111-tile-17', color: 'grey' },
      { id: 'l111-tile-18', color: 'grey' },
      { id: 'l111-tile-19', color: 'blue', isFrozen: true },
      { id: 'l111-tile-20', color: 'grey' },
      { id: 'l111-tile-21', color: 'grey' },
      { id: 'l111-tile-22', color: 'cyan' },
      { id: 'l111-tile-23', color: 'grey' },
      { id: 'l111-tile-24', color: 'grey' },
      { id: 'l111-tile-25', color: 'blue', number: 5, allowedColors: ['blue', 'cyan'] },
    ],
  },
  {
    id: 112,
    title: 'Level 112',
    gridSize: 5,
    initialTiles: [
      { id: 'l112-tile-1', color: 'purple' },
      { id: 'l112-tile-2', color: 'purple', number: 4 },
      { id: 'l112-tile-3', color: 'grey' },
      { id: 'l112-tile-4', color: 'purple', isFrozen: true },
      { id: 'l112-tile-5', color: 'lime' },
      { id: 'l112-tile-6', color: 'grey' },
      { id: 'l112-tile-7', color: 'grey' },
      { id: 'l112-tile-8', color: 'grey' },
      { id: 'l112-tile-9', color: 'grey' },
      { id: 'l112-tile-10', color: 'grey' },
      { id: 'l112-tile-11', color: 'grey' },
      { id: 'l112-tile-12', color: 'purple' },
      { id: 'l112-tile-13', color: 'amber', isFrozen: true },
      { id: 'l112-tile-14', color: 'grey' },
      { id: 'l112-tile-15', color: 'lime', number: 3 },
      { id: 'l112-tile-16', color: 'grey' },
      { id: 'l112-tile-17', color: 'grey' },
      { id: 'l112-tile-18', color: 'lime' },
      { id: 'l112-tile-19', color: 'grey' },
      { id: 'l112-tile-20', color: 'grey' },
      { id: 'l112-tile-21', color: 'orange' },
      { id: 'l112-tile-22', color: 'grey' },
      { id: 'l112-tile-23', color: 'grey' },
      { id: 'l112-tile-24', color: 'orange', number: 4, allowedColors: ['orange', 'amber'] },
      { id: 'l112-tile-25', color: 'orange' },
    ],
  },
  {
    id: 113,
    title: 'Level 113',
    gridSize: 5,
    initialTiles: [
      { id: 'l113-tile-1', color: 'grey' },
      { id: 'l113-tile-2', color: 'grey' },
      { id: 'l113-tile-3', color: 'pink' },
      { id: 'l113-tile-4', color: 'grey' },
      { id: 'l113-tile-5', color: 'pink', number: 3 },
      { id: 'l113-tile-6', color: 'grey' },
      { id: 'l113-tile-7', color: 'grey' },
      { id: 'l113-tile-8', color: 'green' },
      { id: 'l113-tile-9', color: 'grey' },
      { id: 'l113-tile-10', color: 'pink' },
      { id: 'l113-tile-11', color: 'green', number: 4, allowedColors: ['green', 'lime'] },
      { id: 'l113-tile-12', color: 'grey' },
      { id: 'l113-tile-13', color: 'charcoal', isFrozen: true },
      { id: 'l113-tile-14', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l113-tile-15', color: 'grey' },
      { id: 'l113-tile-16', color: 'grey' },
      { id: 'l113-tile-17', color: 'charcoal' },
      { id: 'l113-tile-18', color: 'grey' },
      { id: 'l113-tile-19', color: 'grey' },
      { id: 'l113-tile-20', color: 'grey' },
      { id: 'l113-tile-21', color: 'lime' },
      { id: 'l113-tile-22', color: 'grey' },
      { id: 'l113-tile-23', color: 'charcoal', number: 4 },
      { id: 'l113-tile-24', color: 'grey' },
      { id: 'l113-tile-25', color: 'charcoal' },
    ],
  },
  {
    id: 114,
    title: 'Level 114',
    gridSize: 5,
    initialTiles: [
      { id: 'l114-tile-1', color: 'indigo', number: 4, allowedColors: ['indigo', 'purple'] },
      { id: 'l114-tile-2', color: 'grey' },
      { id: 'l114-tile-3', color: 'indigo' },
      { id: 'l114-tile-4', color: 'grey' },
      { id: 'l114-tile-5', color: 'yellow', number: 3 },
      { id: 'l114-tile-6', color: 'grey' },
      { id: 'l114-tile-7', color: 'grey' },
      { id: 'l114-tile-8', color: 'purple', isFrozen: true },
      { id: 'l114-tile-9', color: 'yellow' },
      { id: 'l114-tile-10', color: 'grey' },
      { id: 'l114-tile-11', color: 'indigo' },
      { id: 'l114-tile-12', color: 'grey' },
      { id: 'l114-tile-13', color: 'red' },
      { id: 'l114-tile-14', color: 'cyan' },
      { id: 'l114-tile-15', color: 'yellow' },
      { id: 'l114-tile-16', color: 'grey' },
      { id: 'l114-tile-17', color: 'grey' },
      { id: 'l114-tile-18', color: 'red', isFrozen: true },
      { id: 'l114-tile-19', color: 'grey' },
      { id: 'l114-tile-20', color: 'cyan' },
      { id: 'l114-tile-21', color: 'red', number: 4, allowedColors: ['red', 'orange'] },
      { id: 'l114-tile-22', color: 'grey' },
      { id: 'l114-tile-23', color: 'orange' },
      { id: 'l114-tile-24', color: 'grey' },
      { id: 'l114-tile-25', color: 'cyan', number: 3 },
    ],
  },
  {
    id: 115,
    title: 'Level 115',
    gridSize: 6,
    initialTiles: [
      { id: 'l115-tile-1', color: 'blue', number: 5, allowedColors: ['blue', 'indigo'] },
      { id: 'l115-tile-2', color: 'grey' },
      { id: 'l115-tile-3', color: 'grey' },
      { id: 'l115-tile-4', color: 'joker', isJoker: true },
      { id: 'l115-tile-5', color: 'grey' },
      { id: 'l115-tile-6', color: 'amber', number: 4 },
      { id: 'l115-tile-7', color: 'grey' },
      { id: 'l115-tile-8', color: 'grey' },
      { id: 'l115-tile-9', color: 'indigo', isFrozen: true },
      { id: 'l115-tile-10', color: 'amber' },
      { id: 'l115-tile-11', color: 'grey' },
      { id: 'l115-tile-12', color: 'grey' },
      { id: 'l115-tile-13', color: 'blue' },
      { id: 'l115-tile-14', color: 'grey' },
      { id: 'l115-tile-15', color: 'blue' },
      { id: 'l115-tile-16', color: 'grey' },
      { id: 'l115-tile-17', color: 'amber', isFrozen: true },
      { id: 'l115-tile-18', color: 'grey' },
      { id: 'l115-tile-19', color: 'grey' },
      { id: 'l115-tile-20', color: 'grey' },
      { id: 'l115-tile-21', color: 'grey' },
      { id: 'l115-tile-22', color: 'lime', isFrozen: true },
      { id: 'l115-tile-23', color: 'grey' },
      { id: 'l115-tile-24', color: 'amber' },
      { id: 'l115-tile-25', color: 'green' },
      { id: 'l115-tile-26', color: 'grey' },
      { id: 'l115-tile-27', color: 'grey' },
      { id: 'l115-tile-28', color: 'grey' },
      { id: 'l115-tile-29', color: 'lime' },
      { id: 'l115-tile-30', color: 'grey' },
      { id: 'l115-tile-31', color: 'grey' },
      { id: 'l115-tile-32', color: 'grey' },
      { id: 'l115-tile-33', color: 'green', number: 5, allowedColors: ['green', 'lime'] },
      { id: 'l115-tile-34', color: 'grey' },
      { id: 'l115-tile-35', color: 'green', isFrozen: true },
      { id: 'l115-tile-36', color: 'grey' },
    ],
  },
  {
    id: 116,
    title: 'Level 116',
    gridSize: 6,
    initialTiles: [
      { id: 'l116-tile-1', color: 'orange' },
      { id: 'l116-tile-2', color: 'grey' },
      { id: 'l116-tile-3', color: 'grey' },
      { id: 'l116-tile-4', color: 'grey' },
      { id: 'l116-tile-5', color: 'grey' },
      { id: 'l116-tile-6', color: 'purple' },
      { id: 'l116-tile-7', color: 'grey' },
      { id: 'l116-tile-8', color: 'orange', number: 4 },
      { id: 'l116-tile-9', color: 'grey' },
      { id: 'l116-tile-10', color: 'grey' },
      { id: 'l116-tile-11', color: 'purple', number: 5, allowedColors: ['purple', 'pink'] },
      { id: 'l116-tile-12', color: 'grey' },
      { id: 'l116-tile-13', color: 'orange', isFrozen: true },
      { id: 'l116-tile-14', color: 'grey' },
      { id: 'l116-tile-15', color: 'joker', isJoker: true },
      { id: 'l116-tile-16', color: 'grey' },
      { id: 'l116-tile-17', color: 'grey' },
      { id: 'l116-tile-18', color: 'purple', isFrozen: true },
      { id: 'l116-tile-19', color: 'orange' },
      { id: 'l116-tile-20', color: 'grey' },
      { id: 'l116-tile-21', color: 'cyan', isFrozen: true },
      { id: 'l116-tile-22', color: 'grey' },
      { id: 'l116-tile-23', color: 'grey' },
      { id: 'l116-tile-24', color: 'pink' },
      { id: 'l116-tile-25', color: 'grey' },
      { id: 'l116-tile-26', color: 'cyan', number: 4, allowedColors: ['cyan', 'blue'] },
      { id: 'l116-tile-27', color: 'grey' },
      { id: 'l116-tile-28', color: 'yellow', isFrozen: true },
      { id: 'l116-tile-29', color: 'yellow', number: 3 },
      { id: 'l116-tile-30', color: 'grey' },
      { id: 'l116-tile-31', color: 'cyan' },
      { id: 'l116-tile-32', color: 'grey' },
      { id: 'l116-tile-33', color: 'blue' },
      { id: 'l116-tile-34', color: 'grey' },
      { id: 'l116-tile-35', color: 'grey' },
      { id: 'l116-tile-36', color: 'yellow' },
    ],
  },
  {
    id: 117,
    title: 'Level 117',
    gridSize: 6,
    initialTiles: [
      { id: 'l117-tile-1', color: 'red' },
      { id: 'l117-tile-2', color: 'grey' },
      { id: 'l117-tile-3', color: 'red', number: 5, allowedColors: ['red', 'orange', 'pink'] },
      { id: 'l117-tile-4', color: 'grey' },
      { id: 'l117-tile-5', color: 'orange' },
      { id: 'l117-tile-6', color: 'charcoal' },
      { id: 'l117-tile-7', color: 'blue' },
      { id: 'l117-tile-8', color: 'pink', isFrozen: true },
      { id: 'l117-tile-9', color: 'grey' },
      { id: 'l117-tile-10', color: 'grey' },
      { id: 'l117-tile-11', color: 'grey' },
      { id: 'l117-tile-12', color: 'grey' },
      { id: 'l117-tile-13', color: 'grey' },
      { id: 'l117-tile-14', color: 'grey' },
      { id: 'l117-tile-15', color: 'joker', isJoker: true },
      { id: 'l117-tile-16', color: 'charcoal', isFrozen: true },
      { id: 'l117-tile-17', color: 'grey' },
      { id: 'l117-tile-18', color: 'charcoal', number: 4 },
      { id: 'l117-tile-19', color: 'blue', number: 4 },
      { id: 'l117-tile-20', color: 'grey' },
      { id: 'l117-tile-21', color: 'blue', isFrozen: true },
      { id: 'l117-tile-22', color: 'green', isFrozen: true },
      { id: 'l117-tile-23', color: 'grey' },
      { id: 'l117-tile-24', color: 'grey' },
      { id: 'l117-tile-25', color: 'grey' },
      { id: 'l117-tile-26', color: 'grey' },
      { id: 'l117-tile-27', color: 'lime', isFrozen: true },
      { id: 'l117-tile-28', color: 'grey' },
      { id: 'l117-tile-29', color: 'grey' },
      { id: 'l117-tile-30', color: 'charcoal' },
      { id: 'l117-tile-31', color: 'blue' },
      { id: 'l117-tile-32', color: 'lime' },
      { id: 'l117-tile-33', color: 'grey' },
      { id: 'l117-tile-34', color: 'lime', number: 5, allowedColors: ['lime', 'green'] },
      { id: 'l117-tile-35', color: 'grey' },
      { id: 'l117-tile-36', color: 'green' },
    ],
  },
  {
    id: 118,
    title: 'Level 118',
    gridSize: 6,
    initialTiles: [
      { id: 'l118-tile-1', color: 'pink', number: 4 },
      { id: 'l118-tile-2', color: 'grey' },
      { id: 'l118-tile-3', color: 'pink' },
      { id: 'l118-tile-4', color: 'joker', isJoker: true },
      { id: 'l118-tile-5', color: 'grey' },
      { id: 'l118-tile-6', color: 'indigo', number: 5, allowedColors: ['indigo', 'blue'] },
      { id: 'l118-tile-7', color: 'grey' },
      { id: 'l118-tile-8', color: 'grey' },
      { id: 'l118-tile-9', color: 'grey' },
      { id: 'l118-tile-10', color: 'indigo' },
      { id: 'l118-tile-11', color: 'grey' },
      { id: 'l118-tile-12', color: 'grey' },
      { id: 'l118-tile-13', color: 'pink' },
      { id: 'l118-tile-14', color: 'pink', isFrozen: true },
      { id: 'l118-tile-15', color: 'grey' },
      { id: 'l118-tile-16', color: 'grey' },
      { id: 'l118-tile-17', color: 'indigo', isFrozen: true },
      { id: 'l118-tile-18', color: 'blue' },
      { id: 'l118-tile-19', color: 'amber' },
      { id: 'l118-tile-20', color: 'amber', isFrozen: true },
      { id: 'l118-tile-21', color: 'grey' },
      { id: 'l118-tile-22', color: 'grey' },
      { id: 'l118-tile-23', color: 'cyan' },
      { id: 'l118-tile-24', color: 'cyan' },
      { id: 'l118-tile-25', color: 'grey' },
      { id: 'l118-tile-26', color: 'grey' },
      { id: 'l118-tile-27', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l118-tile-28', color: 'cyan', isFrozen: true },
      { id: 'l118-tile-29', color: 'grey' },
      { id: 'l118-tile-30', color: 'grey' },
      { id: 'l118-tile-31', color: 'amber', number: 5, allowedColors: ['amber', 'yellow'] },
      { id: 'l118-tile-32', color: 'grey' },
      { id: 'l118-tile-33', color: 'grey' },
      { id: 'l118-tile-34', color: 'yellow' },
      { id: 'l118-tile-35', color: 'grey' },
      { id: 'l118-tile-36', color: 'cyan', number: 4 },
    ],
  },
  {
    id: 119,
    title: 'Level 119',
    gridSize: 6,
    initialTiles: [
      { id: 'l119-tile-1', color: 'grey' },
      { id: 'l119-tile-2', color: 'purple' },
      { id: 'l119-tile-3', color: 'grey' },
      { id: 'l119-tile-4', color: 'green', number: 5, allowedColors: ['green', 'cyan'] },
      { id: 'l119-tile-5', color: 'grey' },
      { id: 'l119-tile-6', color: 'cyan' },
      { id: 'l119-tile-7', color: 'purple', number: 4 },
      { id: 'l119-tile-8', color: 'grey' },
      { id: 'l119-tile-9', color: 'green' },
      { id: 'l119-tile-10', color: 'grey' },
      { id: 'l119-tile-11', color: 'grey' },
      { id: 'l119-tile-12', color: 'red' },
      { id: 'l119-tile-13', color: 'grey' },
      { id: 'l119-tile-14', color: 'purple', isFrozen: true },
      { id: 'l119-tile-15', color: 'grey' },
      { id: 'l119-tile-16', color: 'green', isFrozen: true },
      { id: 'l119-tile-17', color: 'joker', isJoker: true },
      { id: 'l119-tile-18', color: 'grey' },
      { id: 'l119-tile-19', color: 'purple' },
      { id: 'l119-tile-20', color: 'grey' },
      { id: 'l119-tile-21', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l119-tile-22', color: 'red', isFrozen: true },
      { id: 'l119-tile-23', color: 'grey' },
      { id: 'l119-tile-24', color: 'red', number: 5, allowedColors: ['red', 'amber'] },
      { id: 'l119-tile-25', color: 'grey' },
      { id: 'l119-tile-26', color: 'orange', isFrozen: true },
      { id: 'l119-tile-27', color: 'grey' },
      { id: 'l119-tile-28', color: 'grey' },
      { id: 'l119-tile-29', color: 'grey' },
      { id: 'l119-tile-30', color: 'grey' },
      { id: 'l119-tile-31', color: 'orange' },
      { id: 'l119-tile-32', color: 'grey' },
      { id: 'l119-tile-33', color: 'orange', number: 4 },
      { id: 'l119-tile-34', color: 'grey' },
      { id: 'l119-tile-35', color: 'orange' },
      { id: 'l119-tile-36', color: 'amber' },
    ],
  },
  {
    id: 120,
    title: 'Level 120',
    gridSize: 6,
    initialTiles: [
      { id: 'l120-tile-1', color: 'grey' },
      { id: 'l120-tile-2', color: 'blue', number: 5, allowedColors: ['blue', 'purple'] },
      { id: 'l120-tile-3', color: 'grey' },
      { id: 'l120-tile-4', color: 'purple' },
      { id: 'l120-tile-5', color: 'yellow' },
      { id: 'l120-tile-6', color: 'grey' },
      { id: 'l120-tile-7', color: 'blue' },
      { id: 'l120-tile-8', color: 'grey' },
      { id: 'l120-tile-9', color: 'grey' },
      { id: 'l120-tile-10', color: 'grey' },
      { id: 'l120-tile-11', color: 'grey' },
      { id: 'l120-tile-12', color: 'yellow', number: 4 },
      { id: 'l120-tile-13', color: 'lime' },
      { id: 'l120-tile-14', color: 'blue', isFrozen: true },
      { id: 'l120-tile-15', color: 'joker', isJoker: true },
      { id: 'l120-tile-16', color: 'grey' },
      { id: 'l120-tile-17', color: 'yellow', isFrozen: true },
      { id: 'l120-tile-18', color: 'grey' },
      { id: 'l120-tile-19', color: 'grey' },
      { id: 'l120-tile-20', color: 'lime', isFrozen: true },
      { id: 'l120-tile-21', color: 'grey' },
      { id: 'l120-tile-22', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l120-tile-23', color: 'charcoal', isFrozen: true },
      { id: 'l120-tile-24', color: 'yellow' },
      { id: 'l120-tile-25', color: 'lime', number: 4 },
      { id: 'l120-tile-26', color: 'grey' },
      { id: 'l120-tile-27', color: 'grey' },
      { id: 'l120-tile-28', color: 'grey' },
      { id: 'l120-tile-29', color: 'grey' },
      { id: 'l120-tile-30', color: 'indigo' },
      { id: 'l120-tile-31', color: 'grey' },
      { id: 'l120-tile-32', color: 'lime' },
      { id: 'l120-tile-33', color: 'charcoal' },
      { id: 'l120-tile-34', color: 'grey' },
      { id: 'l120-tile-35', color: 'charcoal', number: 5, allowedColors: ['charcoal', 'indigo'] },
      { id: 'l120-tile-36', color: 'grey' },
    ],
  },
  {
    id: 121,
    title: 'Level 121',
    gridSize: 6,
    initialTiles: [
      { id: 'l121-tile-1', color: 'cyan', number: 5, allowedColors: ['cyan', 'lime', 'green'] },
      { id: 'l121-tile-2', color: 'grey' },
      { id: 'l121-tile-3', color: 'lime' },
      { id: 'l121-tile-4', color: 'grey' },
      { id: 'l121-tile-5', color: 'pink', number: 4 },
      { id: 'l121-tile-6', color: 'grey' },
      { id: 'l121-tile-7', color: 'grey' },
      { id: 'l121-tile-8', color: 'grey' },
      { id: 'l121-tile-9', color: 'cyan', isFrozen: true },
      { id: 'l121-tile-10', color: 'green' },
      { id: 'l121-tile-11', color: 'grey' },
      { id: 'l121-tile-12', color: 'pink' },
      { id: 'l121-tile-13', color: 'grey' },
      { id: 'l121-tile-14', color: 'grey' },
      { id: 'l121-tile-15', color: 'amber', isFrozen: true },
      { id: 'l121-tile-16', color: 'grey' },
      { id: 'l121-tile-17', color: 'pink' },
      { id: 'l121-tile-18', color: 'pink' },
      { id: 'l121-tile-19', color: 'joker', isJoker: true },
      { id: 'l121-tile-20', color: 'amber', number: 4, allowedColors: ['amber', 'orange'] },
      { id: 'l121-tile-21', color: 'grey' },
      { id: 'l121-tile-22', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l121-tile-23', color: 'grey' },
      { id: 'l121-tile-24', color: 'indigo' },
      { id: 'l121-tile-25', color: 'grey' },
      { id: 'l121-tile-26', color: 'grey' },
      { id: 'l121-tile-27', color: 'amber', isFrozen: true },
      { id: 'l121-tile-28', color: 'indigo', isFrozen: true },
      { id: 'l121-tile-29', color: 'grey' },
      { id: 'l121-tile-30', color: 'grey' },
      { id: 'l121-tile-31', color: 'grey' },
      { id: 'l121-tile-32', color: 'orange' },
      { id: 'l121-tile-33', color: 'indigo' },
      { id: 'l121-tile-34', color: 'grey' },
      { id: 'l121-tile-35', color: 'grey' },
      { id: 'l121-tile-36', color: 'indigo', number: 5 },
    ],
  },
  {
    id: 122,
    title: 'Level 122',
    gridSize: 6,
    initialTiles: [
      { id: 'l122-tile-1', color: 'grey' },
      { id: 'l122-tile-2', color: 'orange' },
      { id: 'l122-tile-3', color: 'grey' },
      { id: 'l122-tile-4', color: 'orange' },
      { id: 'l122-tile-5', color: 'grey' },
      { id: 'l122-tile-6', color: 'purple', number: 5, allowedColors: ['purple', 'indigo'] },
      { id: 'l122-tile-7', color: 'grey' },
      { id: 'l122-tile-8', color: 'grey' },
      { id: 'l122-tile-9', color: 'orange', number: 4 },
      { id: 'l122-tile-10', color: 'grey' },
      { id: 'l122-tile-11', color: 'grey' },
      { id: 'l122-tile-12', color: 'grey' },
      { id: 'l122-tile-13', color: 'joker', isJoker: true },
      { id: 'l122-tile-14', color: 'orange', isFrozen: true },
      { id: 'l122-tile-15', color: 'grey' },
      { id: 'l122-tile-16', color: 'green', isFrozen: true },
      { id: 'l122-tile-17', color: 'purple' },
      { id: 'l122-tile-18', color: 'grey' },
      { id: 'l122-tile-19', color: 'grey' },
      { id: 'l122-tile-20', color: 'pink', isFrozen: true },
      { id: 'l122-tile-21', color: 'green', isFrozen: true },
      { id: 'l122-tile-22', color: 'grey' },
      { id: 'l122-tile-23', color: 'purple', isFrozen: true },
      { id: 'l122-tile-24', color: 'indigo' },
      { id: 'l122-tile-25', color: 'grey' },
      { id: 'l122-tile-26', color: 'grey' },
      { id: 'l122-tile-27', color: 'red', isFrozen: true },
      { id: 'l122-tile-28', color: 'green', number: 4 },
      { id: 'l122-tile-29', color: 'grey' },
      { id: 'l122-tile-30', color: 'joker', isJoker: true },
      { id: 'l122-tile-31', color: 'red', number: 5, allowedColors: ['red', 'pink'] },
      { id: 'l122-tile-32', color: 'grey' },
      { id: 'l122-tile-33', color: 'red' },
      { id: 'l122-tile-34', color: 'grey' },
      { id: 'l122-tile-35', color: 'green' },
      { id: 'l122-tile-36', color: 'grey' },
    ],
  },
  {
    id: 123,
    title: 'Level 123',
    gridSize: 6,
    initialTiles: [
      { id: 'l123-tile-1', color: 'yellow' },
      { id: 'l123-tile-2', color: 'grey' },
      { id: 'l123-tile-3', color: 'yellow', number: 5, allowedColors: ['yellow', 'amber'] },
      { id: 'l123-tile-4', color: 'grey' },
      { id: 'l123-tile-5', color: 'amber' },
      { id: 'l123-tile-6', color: 'grey' },
      { id: 'l123-tile-7', color: 'grey' },
      { id: 'l123-tile-8', color: 'yellow', isFrozen: true },
      { id: 'l123-tile-9', color: 'grey' },
      { id: 'l123-tile-10', color: 'grey' },
      { id: 'l123-tile-11', color: 'blue' },
      { id: 'l123-tile-12', color: 'cyan' },
      { id: 'l123-tile-13', color: 'blue', number: 4 },
      { id: 'l123-tile-14', color: 'grey' },
      { id: 'l123-tile-15', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l123-tile-16', color: 'charcoal', isFrozen: true },
      { id: 'l123-tile-17', color: 'grey' },
      { id: 'l123-tile-18', color: 'grey' },
      { id: 'l123-tile-19', color: 'pink' },
      { id: 'l123-tile-20', color: 'blue', isFrozen: true },
      { id: 'l123-tile-21', color: 'charcoal', isFrozen: true },
      { id: 'l123-tile-22', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l123-tile-23', color: 'grey' },
      { id: 'l123-tile-24', color: 'cyan', number: 5, allowedColors: ['cyan', 'lime'] },
      { id: 'l123-tile-25', color: 'blue' },
      { id: 'l123-tile-26', color: 'pink' },
      { id: 'l123-tile-27', color: 'charcoal' },
      { id: 'l123-tile-28', color: 'grey' },
      { id: 'l123-tile-29', color: 'cyan' },
      { id: 'l123-tile-30', color: 'grey' },
      { id: 'l123-tile-31', color: 'grey' },
      { id: 'l123-tile-32', color: 'pink', number: 3 },
      { id: 'l123-tile-33', color: 'grey' },
      { id: 'l123-tile-34', color: 'charcoal', number: 4 },
      { id: 'l123-tile-35', color: 'grey' },
      { id: 'l123-tile-36', color: 'lime' },
    ],
  },
  {
    id: 124,
    title: 'Level 124',
    gridSize: 6,
    initialTiles: [
      { id: 'l124-tile-1', color: 'indigo', number: 4 },
      { id: 'l124-tile-2', color: 'grey' },
      { id: 'l124-tile-3', color: 'indigo' },
      { id: 'l124-tile-4', color: 'lime' },
      { id: 'l124-tile-5', color: 'grey' },
      { id: 'l124-tile-6', color: 'grey' },
      { id: 'l124-tile-7', color: 'grey' },
      { id: 'l124-tile-8', color: 'grey' },
      { id: 'l124-tile-9', color: 'grey' },
      { id: 'l124-tile-10', color: 'grey' },
      { id: 'l124-tile-11', color: 'green', number: 5, allowedColors: ['green', 'lime', 'cyan'] },
      { id: 'l124-tile-12', color: 'grey' },
      { id: 'l124-tile-13', color: 'indigo' },
      { id: 'l124-tile-14', color: 'indigo', isFrozen: true },
      { id: 'l124-tile-15', color: 'grey' },
      { id: 'l124-tile-16', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l124-tile-17', color: 'grey' },
      { id: 'l124-tile-18', color: 'cyan', isFrozen: true },
      { id: 'l124-tile-19', color: 'orange' },
      { id: 'l124-tile-20', color: 'grey' },
      { id: 'l124-tile-21', color: 'orange', isFrozen: true },
      { id: 'l124-tile-22', color: 'grey' },
      { id: 'l124-tile-23', color: 'green', isFrozen: true },
      { id: 'l124-tile-24', color: 'purple' },
      { id: 'l124-tile-25', color: 'grey' },
      { id: 'l124-tile-26', color: 'orange', number: 5, allowedColors: ['orange', 'red'] },
      { id: 'l124-tile-27', color: 'grey' },
      { id: 'l124-tile-28', color: 'purple', isFrozen: true },
      { id: 'l124-tile-29', color: 'grey' },
      { id: 'l124-tile-30', color: 'grey' },
      { id: 'l124-tile-31', color: 'joker', isJoker: true },
      { id: 'l124-tile-32', color: 'grey' },
      { id: 'l124-tile-33', color: 'red' },
      { id: 'l124-tile-34', color: 'purple' },
      { id: 'l124-tile-35', color: 'grey' },
      { id: 'l124-tile-36', color: 'purple', number: 4 },
    ],
  },
  {
    id: 125,
    title: 'Level 125',
    gridSize: 6,
    initialTiles: [
      { id: 'l125-tile-1', color: 'grey' },
      { id: 'l125-tile-2', color: 'red' },
      { id: 'l125-tile-3', color: 'grey' },
      { id: 'l125-tile-4', color: 'red', number: 4 },
      { id: 'l125-tile-5', color: 'grey' },
      { id: 'l125-tile-6', color: 'charcoal' },
      { id: 'l125-tile-7', color: 'grey' },
      { id: 'l125-tile-8', color: 'lime', number: 3 },
      { id: 'l125-tile-9', color: 'blue' },
      { id: 'l125-tile-10', color: 'grey' },
      { id: 'l125-tile-11', color: 'lime' },
      { id: 'l125-tile-12', color: 'red' },
      { id: 'l125-tile-13', color: 'grey' },
      { id: 'l125-tile-14', color: 'cyan', isFrozen: true },
      { id: 'l125-tile-15', color: 'grey' },
      { id: 'l125-tile-16', color: 'joker', isJoker: true },
      { id: 'l125-tile-17', color: 'amber', isFrozen: true },
      { id: 'l125-tile-18', color: 'amber', number: 5, allowedColors: ['amber', 'yellow'] },
      { id: 'l125-tile-19', color: 'charcoal', number: 4 },
      { id: 'l125-tile-20', color: 'blue' },
      { id: 'l125-tile-21', color: 'grey' },
      { id: 'l125-tile-22', color: 'grey' },
      { id: 'l125-tile-23', color: 'charcoal', isFrozen: true },
      { id: 'l125-tile-24', color: 'yellow' },
      { id: 'l125-tile-25', color: 'cyan', isFrozen: true },
      { id: 'l125-tile-26', color: 'grey' },
      { id: 'l125-tile-27', color: 'grey' },
      { id: 'l125-tile-28', color: 'grey' },
      { id: 'l125-tile-29', color: 'grey' },
      { id: 'l125-tile-30', color: 'charcoal' },
      { id: 'l125-tile-31', color: 'amber', isFrozen: true },
      { id: 'l125-tile-32', color: 'grey' },
      { id: 'l125-tile-33', color: 'blue', number: 5, allowedColors: ['blue', 'cyan'] },
      { id: 'l125-tile-34', color: 'grey' },
      { id: 'l125-tile-35', color: 'lime' },
      { id: 'l125-tile-36', color: 'red', isFrozen: true },
    ],
  },
  {
    id: 126,
    title: 'Level 126',
    gridSize: 6,
    initialTiles: [
      { id: 'l126-tile-1', color: 'purple', number: 4 },
      { id: 'l126-tile-2', color: 'purple' },
      { id: 'l126-tile-3', color: 'orange', isFrozen: true },
      { id: 'l126-tile-4', color: 'blue' },
      { id: 'l126-tile-5', color: 'grey' },
      { id: 'l126-tile-6', color: 'cyan', number: 5, allowedColors: ['cyan', 'blue'] },
      { id: 'l126-tile-7', color: 'pink' },
      { id: 'l126-tile-8', color: 'lime' },
      { id: 'l126-tile-9', color: 'grey' },
      { id: 'l126-tile-10', color: 'pink' },
      { id: 'l126-tile-11', color: 'purple', isFrozen: true },
      { id: 'l126-tile-12', color: 'grey' },
      { id: 'l126-tile-13', color: 'grey' },
      { id: 'l126-tile-14', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l126-tile-15', color: 'pink', number: 3 },
      { id: 'l126-tile-16', color: 'amber' },
      { id: 'l126-tile-17', color: 'grey' },
      { id: 'l126-tile-18', color: 'grey' },
      { id: 'l126-tile-19', color: 'blue', isFrozen: true },
      { id: 'l126-tile-20', color: 'grey' },
      { id: 'l126-tile-21', color: 'grey' },
      { id: 'l126-tile-22', color: 'grey' },
      { id: 'l126-tile-23', color: 'grey' },
      { id: 'l126-tile-24', color: 'purple' },
      { id: 'l126-tile-25', color: 'grey' },
      { id: 'l126-tile-26', color: 'grey' },
      { id: 'l126-tile-27', color: 'cyan', isFrozen: true },
      { id: 'l126-tile-28', color: 'grey' },
      { id: 'l126-tile-29', color: 'lime' },
      { id: 'l126-tile-30', color: 'grey' },
      { id: 'l126-tile-31', color: 'orange', number: 4, allowedColors: ['orange', 'amber'] },
      { id: 'l126-tile-32', color: 'lime', isFrozen: true },
      { id: 'l126-tile-33', color: 'grey' },
      { id: 'l126-tile-34', color: 'grey' },
      { id: 'l126-tile-35', color: 'amber' },
      { id: 'l126-tile-36', color: 'lime', number: 4 },
    ],
  },
  {
    id: 127,
    title: 'Level 127',
    gridSize: 6,
    initialTiles: [
      { id: 'l127-tile-1', color: 'grey' },
      { id: 'l127-tile-2', color: 'green', number: 5, allowedColors: ['green', 'lime'] },
      { id: 'l127-tile-3', color: 'grey' },
      { id: 'l127-tile-4', color: 'amber', isFrozen: true },
      { id: 'l127-tile-5', color: 'charcoal', number: 4 },
      { id: 'l127-tile-6', color: 'grey' },
      { id: 'l127-tile-7', color: 'pink' },
      { id: 'l127-tile-8', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l127-tile-9', color: 'red' },
      { id: 'l127-tile-10', color: 'grey' },
      { id: 'l127-tile-11', color: 'indigo' },
      { id: 'l127-tile-12', color: 'amber' },
      { id: 'l127-tile-13', color: 'grey' },
      { id: 'l127-tile-14', color: 'charcoal', isFrozen: true },
      { id: 'l127-tile-15', color: 'yellow', number: 4, allowedColors: ['yellow', 'amber'] },
      { id: 'l127-tile-16', color: 'green', isFrozen: true },
      { id: 'l127-tile-17', color: 'charcoal' },
      { id: 'l127-tile-18', color: 'grey' },
      { id: 'l127-tile-19', color: 'grey' },
      { id: 'l127-tile-20', color: 'grey' },
      { id: 'l127-tile-21', color: 'grey' },
      { id: 'l127-tile-22', color: 'grey' },
      { id: 'l127-tile-23', color: 'red' },
      { id: 'l127-tile-24', color: 'charcoal' },
      { id: 'l127-tile-25', color: 'indigo' },
      { id: 'l127-tile-26', color: 'grey' },
      { id: 'l127-tile-27', color: 'lime' },
      { id: 'l127-tile-28', color: 'grey' },
      { id: 'l127-tile-29', color: 'green', isFrozen: true },
      { id: 'l127-tile-30', color: 'grey' },
      { id: 'l127-tile-31', color: 'indigo' },
      { id: 'l127-tile-32', color: 'red', number: 5, allowedColors: ['red', 'pink'] },
      { id: 'l127-tile-33', color: 'yellow' },
      { id: 'l127-tile-34', color: 'grey' },
      { id: 'l127-tile-35', color: 'indigo', number: 4 },
      { id: 'l127-tile-36', color: 'joker', isJoker: true, isFrozen: true },
    ],
  },
  {
    id: 128,
    title: 'Level 128',
    gridSize: 6,
    initialTiles: [
      { id: 'l128-tile-1', color: 'amber', number: 4, allowedColors: ['amber', 'yellow'] },
      { id: 'l128-tile-2', color: 'grey' },
      { id: 'l128-tile-3', color: 'red', isFrozen: true },
      { id: 'l128-tile-4', color: 'blue' },
      { id: 'l128-tile-5', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l128-tile-6', color: 'blue', number: 5, allowedColors: ['blue', 'cyan'] },
      { id: 'l128-tile-7', color: 'purple' },
      { id: 'l128-tile-8', color: 'pink' },
      { id: 'l128-tile-9', color: 'grey' },
      { id: 'l128-tile-10', color: 'grey' },
      { id: 'l128-tile-11', color: 'grey' },
      { id: 'l128-tile-12', color: 'green' },
      { id: 'l128-tile-13', color: 'cyan', isFrozen: true },
      { id: 'l128-tile-14', color: 'amber' },
      { id: 'l128-tile-15', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l128-tile-16', color: 'red', number: 3 },
      { id: 'l128-tile-17', color: 'grey' },
      { id: 'l128-tile-18', color: 'grey' },
      { id: 'l128-tile-19', color: 'grey' },
      { id: 'l128-tile-20', color: 'yellow', isFrozen: true },
      { id: 'l128-tile-21', color: 'grey' },
      { id: 'l128-tile-22', color: 'green' },
      { id: 'l128-tile-23', color: 'green' },
      { id: 'l128-tile-24', color: 'blue' },
      { id: 'l128-tile-25', color: 'grey' },
      { id: 'l128-tile-26', color: 'grey' },
      { id: 'l128-tile-27', color: 'amber' },
      { id: 'l128-tile-28', color: 'purple', isFrozen: true },
      { id: 'l128-tile-29', color: 'grey' },
      { id: 'l128-tile-30', color: 'grey' },
      { id: 'l128-tile-31', color: 'purple', number: 5, allowedColors: ['purple', 'pink'] },
      { id: 'l128-tile-32', color: 'grey' },
      { id: 'l128-tile-33', color: 'grey' },
      { id: 'l128-tile-34', color: 'grey' },
      { id: 'l128-tile-35', color: 'red' },
      { id: 'l128-tile-36', color: 'green', number: 4 },
    ],
  },
  {
    id: 129,
    title: 'Level 129',
    gridSize: 6,
    initialTiles: [
      { id: 'l129-tile-1', color: 'grey' },
      { id: 'l129-tile-2', color: 'lime', number: 4, allowedColors: ['lime', 'green'] },
      { id: 'l129-tile-3', color: 'grey' },
      { id: 'l129-tile-4', color: 'grey' },
      { id: 'l129-tile-5', color: 'orange' },
      { id: 'l129-tile-6', color: 'grey' },
      { id: 'l129-tile-7', color: 'purple', isFrozen: true },
      { id: 'l129-tile-8', color: 'grey' },
      { id: 'l129-tile-9', color: 'green' },
      { id: 'l129-tile-10', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l129-tile-11', color: 'orange', number: 5, allowedColors: ['orange', 'red'] },
      { id: 'l129-tile-12', color: 'indigo', isFrozen: true },
      { id: 'l129-tile-13', color: 'purple', isFrozen: true },
      { id: 'l129-tile-14', color: 'lime', isFrozen: true },
      { id: 'l129-tile-15', color: 'purple', number: 3 },
      { id: 'l129-tile-16', color: 'grey' },
      { id: 'l129-tile-17', color: 'grey' },
      { id: 'l129-tile-18', color: 'orange' },
      { id: 'l129-tile-19', color: 'cyan' },
      { id: 'l129-tile-20', color: 'red' },
      { id: 'l129-tile-21', color: 'grey' },
      { id: 'l129-tile-22', color: 'cyan' },
      { id: 'l129-tile-23', color: 'charcoal' },
      { id: 'l129-tile-24', color: 'charcoal' },
      { id: 'l129-tile-25', color: 'grey' },
      { id: 'l129-tile-26', color: 'cyan', number: 4 },
      { id: 'l129-tile-27', color: 'cyan' },
      { id: 'l129-tile-28', color: 'lime', isFrozen: true },
      { id: 'l129-tile-29', color: 'grey' },
      { id: 'l129-tile-30', color: 'grey' },
      { id: 'l129-tile-31', color: 'joker', isJoker: true },
      { id: 'l129-tile-32', color: 'grey' },
      { id: 'l129-tile-33', color: 'grey' },
      { id: 'l129-tile-34', color: 'grey' },
      { id: 'l129-tile-35', color: 'charcoal', number: 5, allowedColors: ['charcoal', 'indigo'] },
      { id: 'l129-tile-36', color: 'grey' },
    ],
  },
  {
    id: 130,
    title: 'Level 130',
    gridSize: 6,
    initialTiles: [
      { id: 'l130-tile-1', color: 'pink', number: 5, allowedColors: ['pink', 'purple'] },
      { id: 'l130-tile-2', color: 'pink', isFrozen: true },
      { id: 'l130-tile-3', color: 'grey' },
      { id: 'l130-tile-4', color: 'grey' },
      { id: 'l130-tile-5', color: 'indigo' },
      { id: 'l130-tile-6', color: 'yellow', number: 4 },
      { id: 'l130-tile-7', color: 'grey' },
      { id: 'l130-tile-8', color: 'grey' },
      { id: 'l130-tile-9', color: 'pink' },
      { id: 'l130-tile-10', color: 'blue' },
      { id: 'l130-tile-11', color: 'grey' },
      { id: 'l130-tile-12', color: 'lime' },
      { id: 'l130-tile-13', color: 'yellow' },
      { id: 'l130-tile-14', color: 'grey' },
      { id: 'l130-tile-15', color: 'orange' },
      { id: 'l130-tile-16', color: 'lime', number: 4 },
      { id: 'l130-tile-17', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l130-tile-18', color: 'grey' },
      { id: 'l130-tile-19', color: 'lime' },
      { id: 'l130-tile-20', color: 'yellow' },
      { id: 'l130-tile-21', color: 'yellow' },
      { id: 'l130-tile-22', color: 'grey' },
      { id: 'l130-tile-23', color: 'amber', isFrozen: true },
      { id: 'l130-tile-24', color: 'grey' },
      { id: 'l130-tile-25', color: 'grey' },
      { id: 'l130-tile-26', color: 'grey' },
      { id: 'l130-tile-27', color: 'grey' },
      { id: 'l130-tile-28', color: 'amber', isFrozen: true },
      { id: 'l130-tile-29', color: 'purple' },
      { id: 'l130-tile-30', color: 'lime', isFrozen: true },
      { id: 'l130-tile-31', color: 'blue', number: 5, allowedColors: ['blue', 'indigo'] },
      { id: 'l130-tile-32', color: 'grey' },
      { id: 'l130-tile-33', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l130-tile-34', color: 'blue', isFrozen: true },
      { id: 'l130-tile-35', color: 'grey' },
      { id: 'l130-tile-36', color: 'amber', number: 4, allowedColors: ['amber', 'orange'] },
    ],
  },
  {
    id: 131,
    title: 'Level 131',
    gridSize: 6,
    initialTiles: [
      { id: 'l131-tile-1', color: 'charcoal', isFrozen: true },
      { id: 'l131-tile-2', color: 'indigo', number: 5, allowedColors: ['indigo', 'blue'] },
      { id: 'l131-tile-3', color: 'grey' },
      { id: 'l131-tile-4', color: 'joker', isJoker: true },
      { id: 'l131-tile-5', color: 'charcoal' },
      { id: 'l131-tile-6', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l131-tile-7', color: 'grey' },
      { id: 'l131-tile-8', color: 'charcoal' },
      { id: 'l131-tile-9', color: 'indigo', isFrozen: true },
      { id: 'l131-tile-10', color: 'grey' },
      { id: 'l131-tile-11', color: 'red', isFrozen: true },
      { id: 'l131-tile-12', color: 'green', number: 5, allowedColors: ['green', 'lime'] },
      { id: 'l131-tile-13', color: 'grey' },
      { id: 'l131-tile-14', color: 'grey' },
      { id: 'l131-tile-15', color: 'charcoal', number: 4 },
      { id: 'l131-tile-16', color: 'red', isFrozen: true },
      { id: 'l131-tile-17', color: 'grey' },
      { id: 'l131-tile-18', color: 'blue' },
      { id: 'l131-tile-19', color: 'grey' },
      { id: 'l131-tile-20', color: 'grey' },
      { id: 'l131-tile-21', color: 'grey' },
      { id: 'l131-tile-22', color: 'cyan' },
      { id: 'l131-tile-23', color: 'grey' },
      { id: 'l131-tile-24', color: 'green' },
      { id: 'l131-tile-25', color: 'red', number: 4 },
      { id: 'l131-tile-26', color: 'lime' },
      { id: 'l131-tile-27', color: 'cyan' },
      { id: 'l131-tile-28', color: 'green' },
      { id: 'l131-tile-29', color: 'grey' },
      { id: 'l131-tile-30', color: 'indigo' },
      { id: 'l131-tile-31', color: 'grey' },
      { id: 'l131-tile-32', color: 'grey' },
      { id: 'l131-tile-33', color: 'blue', isFrozen: true },
      { id: 'l131-tile-34', color: 'red', isFrozen: true },
      { id: 'l131-tile-35', color: 'cyan', number: 4, allowedColors: ['cyan', 'blue'] },
      { id: 'l131-tile-36', color: 'grey' },
    ],
  },
  {
    id: 132,
    title: 'Level 132',
    gridSize: 6,
    initialTiles: [
      { id: 'l132-tile-1', color: 'orange', number: 5, allowedColors: ['orange', 'amber'] },
      { id: 'l132-tile-2', color: 'grey' },
      { id: 'l132-tile-3', color: 'grey' },
      { id: 'l132-tile-4', color: 'purple', isFrozen: true },
      { id: 'l132-tile-5', color: 'purple', number: 4 },
      { id: 'l132-tile-6', color: 'grey' },
      { id: 'l132-tile-7', color: 'amber' },
      { id: 'l132-tile-8', color: 'grey' },
      { id: 'l132-tile-9', color: 'purple', isFrozen: true },
      { id: 'l132-tile-10', color: 'grey' },
      { id: 'l132-tile-11', color: 'lime' },
      { id: 'l132-tile-12', color: 'yellow' },
      { id: 'l132-tile-13', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l132-tile-14', color: 'grey' },
      { id: 'l132-tile-15', color: 'yellow', number: 4 },
      { id: 'l132-tile-16', color: 'lime', isFrozen: true },
      { id: 'l132-tile-17', color: 'orange' },
      { id: 'l132-tile-18', color: 'grey' },
      { id: 'l132-tile-19', color: 'grey' },
      { id: 'l132-tile-20', color: 'grey' },
      { id: 'l132-tile-21', color: 'grey' },
      { id: 'l132-tile-22', color: 'grey' },
      { id: 'l132-tile-23', color: 'grey' },
      { id: 'l132-tile-24', color: 'purple' },
      { id: 'l132-tile-25', color: 'pink', isFrozen: true },
      { id: 'l132-tile-26', color: 'grey' },
      { id: 'l132-tile-27', color: 'grey' },
      { id: 'l132-tile-28', color: 'pink' },
      { id: 'l132-tile-29', color: 'yellow' },
      { id: 'l132-tile-30', color: 'orange' },
      { id: 'l132-tile-31', color: 'lime', number: 5, allowedColors: ['lime', 'cyan'] },
      { id: 'l132-tile-32', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l132-tile-33', color: 'cyan' },
      { id: 'l132-tile-34', color: 'pink', isFrozen: true },
      { id: 'l132-tile-35', color: 'yellow' },
      { id: 'l132-tile-36', color: 'pink', number: 4 },
    ],
  },
  {
    id: 133,
    title: 'Level 133',
    gridSize: 6,
    initialTiles: [
      { id: 'l133-tile-1', color: 'joker', isJoker: true },
      { id: 'l133-tile-2', color: 'cyan', number: 5, allowedColors: ['cyan', 'green'] },
      { id: 'l133-tile-3', color: 'grey' },
      { id: 'l133-tile-4', color: 'grey' },
      { id: 'l133-tile-5', color: 'grey' },
      { id: 'l133-tile-6', color: 'red', number: 5, allowedColors: ['red', 'orange'] },
      { id: 'l133-tile-7', color: 'blue' },
      { id: 'l133-tile-8', color: 'red' },
      { id: 'l133-tile-9', color: 'grey' },
      { id: 'l133-tile-10', color: 'charcoal' },
      { id: 'l133-tile-11', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l133-tile-12', color: 'grey' },
      { id: 'l133-tile-13', color: 'cyan', isFrozen: true },
      { id: 'l133-tile-14', color: 'grey' },
      { id: 'l133-tile-15', color: 'amber', number: 3 },
      { id: 'l133-tile-16', color: 'grey' },
      { id: 'l133-tile-17', color: 'grey' },
      { id: 'l133-tile-18', color: 'grey' },
      { id: 'l133-tile-19', color: 'orange' },
      { id: 'l133-tile-20', color: 'grey' },
      { id: 'l133-tile-21', color: 'charcoal' },
      { id: 'l133-tile-22', color: 'grey' },
      { id: 'l133-tile-23', color: 'grey' },
      { id: 'l133-tile-24', color: 'amber' },
      { id: 'l133-tile-25', color: 'charcoal', number: 4 },
      { id: 'l133-tile-26', color: 'red', isFrozen: true },
      { id: 'l133-tile-27', color: 'cyan', isFrozen: true },
      { id: 'l133-tile-28', color: 'purple' },
      { id: 'l133-tile-29', color: 'charcoal', isFrozen: true },
      { id: 'l133-tile-30', color: 'blue' },
      { id: 'l133-tile-31', color: 'grey' },
      { id: 'l133-tile-32', color: 'grey' },
      { id: 'l133-tile-33', color: 'amber', isFrozen: true },
      { id: 'l133-tile-34', color: 'green' },
      { id: 'l133-tile-35', color: 'blue', number: 5, allowedColors: ['blue', 'purple'] },
      { id: 'l133-tile-36', color: 'joker', isJoker: true, isFrozen: true },
    ],
  },
  {
    id: 134,
    title: 'Level 134',
    gridSize: 6,
    initialTiles: [
      { id: 'l134-tile-1', color: 'amber', number: 5, allowedColors: ['amber', 'yellow'] },
      { id: 'l134-tile-2', color: 'indigo', isFrozen: true },
      { id: 'l134-tile-3', color: 'amber' },
      { id: 'l134-tile-4', color: 'grey' },
      { id: 'l134-tile-5', color: 'pink' },
      { id: 'l134-tile-6', color: 'lime', number: 4 },
      { id: 'l134-tile-7', color: 'green', isFrozen: true },
      { id: 'l134-tile-8', color: 'grey' },
      { id: 'l134-tile-9', color: 'pink' },
      { id: 'l134-tile-10', color: 'grey' },
      { id: 'l134-tile-11', color: 'cyan', isFrozen: true },
      { id: 'l134-tile-12', color: 'grey' },
      { id: 'l134-tile-13', color: 'yellow', isFrozen: true },
      { id: 'l134-tile-14', color: 'grey' },
      { id: 'l134-tile-15', color: 'pink', number: 4 },
      { id: 'l134-tile-16', color: 'lime' },
      { id: 'l134-tile-17', color: 'grey' },
      { id: 'l134-tile-18', color: 'indigo' },
      { id: 'l134-tile-19', color: 'lime' },
      { id: 'l134-tile-20', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l134-tile-21', color: 'amber', isFrozen: true },
      { id: 'l134-tile-22', color: 'grey' },
      { id: 'l134-tile-23', color: 'lime', isFrozen: true },
      { id: 'l134-tile-24', color: 'green' },
      { id: 'l134-tile-25', color: 'pink' },
      { id: 'l134-tile-26', color: 'grey' },
      { id: 'l134-tile-27', color: 'grey' },
      { id: 'l134-tile-28', color: 'grey' },
      { id: 'l134-tile-29', color: 'grey' },
      { id: 'l134-tile-30', color: 'purple', isFrozen: true },
      { id: 'l134-tile-31', color: 'indigo', number: 5, allowedColors: ['indigo', 'purple'] },
      { id: 'l134-tile-32', color: 'grey' },
      { id: 'l134-tile-33', color: 'joker', isJoker: true },
      { id: 'l134-tile-34', color: 'joker', isJoker: true },
      { id: 'l134-tile-35', color: 'grey' },
      { id: 'l134-tile-36', color: 'green', number: 5, allowedColors: ['green', 'cyan'] },
    ],
  },
  {
    id: 135,
    title: 'Level 135',
    gridSize: 6,
    initialTiles: [
      { id: 'l135-tile-1', color: 'red', number: 6, allowedColors: ['red', 'orange', 'pink'] },
      { id: 'l135-tile-2', color: 'grey' },
      { id: 'l135-tile-3', color: 'cyan' },
      { id: 'l135-tile-4', color: 'lime', isFrozen: true },
      { id: 'l135-tile-5', color: 'joker', isJoker: true },
      { id: 'l135-tile-6', color: 'blue', number: 6, allowedColors: ['blue', 'indigo', 'cyan'] },
      { id: 'l135-tile-7', color: 'grey' },
      { id: 'l135-tile-8', color: 'yellow', isFrozen: true },
      { id: 'l135-tile-9', color: 'joker', isJoker: true },
      { id: 'l135-tile-10', color: 'joker', isJoker: true },
      { id: 'l135-tile-11', color: 'orange' },
      { id: 'l135-tile-12', color: 'grey' },
      { id: 'l135-tile-13', color: 'purple' },
      { id: 'l135-tile-14', color: 'cyan', isFrozen: true },
      { id: 'l135-tile-15', color: 'yellow', number: 3 },
      { id: 'l135-tile-16', color: 'joker', isJoker: true },
      { id: 'l135-tile-17', color: 'purple' },
      { id: 'l135-tile-18', color: 'indigo' },
      { id: 'l135-tile-19', color: 'yellow' },
      { id: 'l135-tile-20', color: 'grey' },
      { id: 'l135-tile-21', color: 'grey' },
      { id: 'l135-tile-22', color: 'grey' },
      { id: 'l135-tile-23', color: 'blue', isFrozen: true },
      { id: 'l135-tile-24', color: 'blue', isFrozen: true },
      { id: 'l135-tile-25', color: 'pink' },
      { id: 'l135-tile-26', color: 'grey' },
      { id: 'l135-tile-27', color: 'green' },
      { id: 'l135-tile-28', color: 'purple', isFrozen: true },
      { id: 'l135-tile-29', color: 'red', isFrozen: true },
      { id: 'l135-tile-30', color: 'green' },
      { id: 'l135-tile-31', color: 'green', number: 6, allowedColors: ['green', 'lime', 'cyan'] },
      { id: 'l135-tile-32', color: 'grey' },
      { id: 'l135-tile-33', color: 'red', isFrozen: true },
      { id: 'l135-tile-34', color: 'grey' },
      { id: 'l135-tile-35', color: 'grey' },
      { id: 'l135-tile-36', color: 'purple', number: 5 },
    ],
  },
  {
    id: 136,
    title: 'Level 136',
    gridSize: 7,
    initialTiles: [
      { id: 'l136-tile-1', color: 'red', number: 6, allowedColors: ['red', 'orange'] },
      { id: 'l136-tile-2', color: 'amber', isFrozen: true },
      { id: 'l136-tile-3', color: 'grey' },
      { id: 'l136-tile-4', color: 'grey' },
      { id: 'l136-tile-5', color: 'orange' },
      { id: 'l136-tile-6', color: 'cyan' },
      { id: 'l136-tile-7', color: 'blue', number: 5, allowedColors: ['blue', 'cyan'] },
      { id: 'l136-tile-8', color: 'purple', isFrozen: true },
      { id: 'l136-tile-9', color: 'grey' },
      { id: 'l136-tile-10', color: 'grey' },
      { id: 'l136-tile-11', color: 'grey' },
      { id: 'l136-tile-12', color: 'grey' },
      { id: 'l136-tile-13', color: 'lime' },
      { id: 'l136-tile-14', color: 'grey' },
      { id: 'l136-tile-15', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l136-tile-16', color: 'orange' },
      { id: 'l136-tile-17', color: 'grey' },
      { id: 'l136-tile-18', color: 'grey' },
      { id: 'l136-tile-19', color: 'grey' },
      { id: 'l136-tile-20', color: 'joker', isJoker: true },
      { id: 'l136-tile-21', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l136-tile-22', color: 'grey' },
      { id: 'l136-tile-23', color: 'amber' },
      { id: 'l136-tile-24', color: 'red', isFrozen: true },
      { id: 'l136-tile-25', color: 'amber', number: 4 },
      { id: 'l136-tile-26', color: 'grey' },
      { id: 'l136-tile-27', color: 'grey' },
      { id: 'l136-tile-28', color: 'lime', isFrozen: true },
      { id: 'l136-tile-29', color: 'amber' },
      { id: 'l136-tile-30', color: 'grey' },
      { id: 'l136-tile-31', color: 'blue', isFrozen: true },
      { id: 'l136-tile-32', color: 'grey' },
      { id: 'l136-tile-33', color: 'grey' },
      { id: 'l136-tile-34', color: 'green' },
      { id: 'l136-tile-35', color: 'green', isFrozen: true },
      { id: 'l136-tile-36', color: 'purple' },
      { id: 'l136-tile-37', color: 'grey' },
      { id: 'l136-tile-38', color: 'grey' },
      { id: 'l136-tile-39', color: 'grey' },
      { id: 'l136-tile-40', color: 'grey' },
      { id: 'l136-tile-41', color: 'purple' },
      { id: 'l136-tile-42', color: 'grey' },
      { id: 'l136-tile-43', color: 'lime', number: 6, allowedColors: ['lime', 'green'] },
      { id: 'l136-tile-44', color: 'grey' },
      { id: 'l136-tile-45', color: 'joker', isJoker: true },
      { id: 'l136-tile-46', color: 'red' },
      { id: 'l136-tile-47', color: 'grey' },
      { id: 'l136-tile-48', color: 'blue' },
      { id: 'l136-tile-49', color: 'purple', number: 5 },
    ],
  },
  {
    id: 137,
    title: 'Level 137',
    gridSize: 7,
    initialTiles: [
      { id: 'l137-tile-1', color: 'green', number: 6, allowedColors: ['green', 'lime'] },
      { id: 'l137-tile-2', color: 'joker', isJoker: true },
      { id: 'l137-tile-3', color: 'pink' },
      { id: 'l137-tile-4', color: 'grey' },
      { id: 'l137-tile-5', color: 'grey' },
      { id: 'l137-tile-6', color: 'pink', isFrozen: true },
      { id: 'l137-tile-7', color: 'pink', number: 5 },
      { id: 'l137-tile-8', color: 'grey' },
      { id: 'l137-tile-9', color: 'grey' },
      { id: 'l137-tile-10', color: 'grey' },
      { id: 'l137-tile-11', color: 'grey' },
      { id: 'l137-tile-12', color: 'grey' },
      { id: 'l137-tile-13', color: 'grey' },
      { id: 'l137-tile-14', color: 'blue', isFrozen: true },
      { id: 'l137-tile-15', color: 'grey' },
      { id: 'l137-tile-16', color: 'grey' },
      { id: 'l137-tile-17', color: 'indigo', isFrozen: true },
      { id: 'l137-tile-18', color: 'grey' },
      { id: 'l137-tile-19', color: 'grey' },
      { id: 'l137-tile-20', color: 'joker', isJoker: true },
      { id: 'l137-tile-21', color: 'lime', isFrozen: true },
      { id: 'l137-tile-22', color: 'cyan', isFrozen: true },
      { id: 'l137-tile-23', color: 'cyan' },
      { id: 'l137-tile-24', color: 'grey' },
      { id: 'l137-tile-25', color: 'cyan', number: 4 },
      { id: 'l137-tile-26', color: 'grey' },
      { id: 'l137-tile-27', color: 'grey' },
      { id: 'l137-tile-28', color: 'amber' },
      { id: 'l137-tile-29', color: 'grey' },
      { id: 'l137-tile-30', color: 'grey' },
      { id: 'l137-tile-31', color: 'green' },
      { id: 'l137-tile-32', color: 'pink', isFrozen: true },
      { id: 'l137-tile-33', color: 'lime' },
      { id: 'l137-tile-34', color: 'orange' },
      { id: 'l137-tile-35', color: 'grey' },
      { id: 'l137-tile-36', color: 'grey' },
      { id: 'l137-tile-37', color: 'amber' },
      { id: 'l137-tile-38', color: 'grey' },
      { id: 'l137-tile-39', color: 'grey' },
      { id: 'l137-tile-40', color: 'orange', isFrozen: true },
      { id: 'l137-tile-41', color: 'pink' },
      { id: 'l137-tile-42', color: 'indigo', isFrozen: true },
      { id: 'l137-tile-43', color: 'orange', number: 6, allowedColors: ['orange', 'amber'] },
      { id: 'l137-tile-44', color: 'cyan' },
      { id: 'l137-tile-45', color: 'green' },
      { id: 'l137-tile-46', color: 'joker', isJoker: true },
      { id: 'l137-tile-47', color: 'grey' },
      { id: 'l137-tile-48', color: 'grey' },
      { id: 'l137-tile-49', color: 'indigo', number: 5, allowedColors: ['indigo', 'blue'] },
    ],
  },
  {
    id: 138,
    title: 'Level 138',
    gridSize: 7,
    initialTiles: [
      { id: 'l138-tile-1', color: 'cyan', number: 6, allowedColors: ['cyan', 'blue'] },
      { id: 'l138-tile-2', color: 'yellow' },
      { id: 'l138-tile-3', color: 'lime' },
      { id: 'l138-tile-4', color: 'joker', isJoker: true },
      { id: 'l138-tile-5', color: 'indigo' },
      { id: 'l138-tile-6', color: 'pink' },
      { id: 'l138-tile-7', color: 'red', number: 6, allowedColors: ['red', 'pink'] },
      { id: 'l138-tile-8', color: 'grey' },
      { id: 'l138-tile-9', color: 'charcoal' },
      { id: 'l138-tile-10', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l138-tile-11', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l138-tile-12', color: 'grey' },
      { id: 'l138-tile-13', color: 'charcoal', isFrozen: true },
      { id: 'l138-tile-14', color: 'grey' },
      { id: 'l138-tile-15', color: 'blue' },
      { id: 'l138-tile-16', color: 'grey' },
      { id: 'l138-tile-17', color: 'red', isFrozen: true },
      { id: 'l138-tile-18', color: 'grey' },
      { id: 'l138-tile-19', color: 'yellow' },
      { id: 'l138-tile-20', color: 'yellow' },
      { id: 'l138-tile-21', color: 'grey' },
      { id: 'l138-tile-22', color: 'grey' },
      { id: 'l138-tile-23', color: 'grey' },
      { id: 'l138-tile-24', color: 'cyan', isFrozen: true },
      { id: 'l138-tile-25', color: 'lime', number: 4 },
      { id: 'l138-tile-26', color: 'grey' },
      { id: 'l138-tile-27', color: 'blue' },
      { id: 'l138-tile-28', color: 'grey' },
      { id: 'l138-tile-29', color: 'grey' },
      { id: 'l138-tile-30', color: 'yellow', isFrozen: true },
      { id: 'l138-tile-31', color: 'grey' },
      { id: 'l138-tile-32', color: 'pink', isFrozen: true },
      { id: 'l138-tile-33', color: 'grey' },
      { id: 'l138-tile-34', color: 'grey' },
      { id: 'l138-tile-35', color: 'grey' },
      { id: 'l138-tile-36', color: 'lime', isFrozen: true },
      { id: 'l138-tile-37', color: 'indigo' },
      { id: 'l138-tile-38', color: 'grey' },
      { id: 'l138-tile-39', color: 'grey' },
      { id: 'l138-tile-40', color: 'grey' },
      { id: 'l138-tile-41', color: 'cyan' },
      { id: 'l138-tile-42', color: 'grey' },
      { id: 'l138-tile-43', color: 'yellow', number: 5 },
      { id: 'l138-tile-44', color: 'lime' },
      { id: 'l138-tile-45', color: 'grey' },
      { id: 'l138-tile-46', color: 'grey' },
      { id: 'l138-tile-47', color: 'red' },
      { id: 'l138-tile-48', color: 'grey' },
      { id: 'l138-tile-49', color: 'charcoal', number: 6, allowedColors: ['charcoal', 'indigo'] },
    ],
  },
  {
    id: 139,
    title: 'Level 139',
    gridSize: 7,
    initialTiles: [
      { id: 'l139-tile-1', color: 'amber', number: 6, allowedColors: ['amber', 'orange'] },
      { id: 'l139-tile-2', color: 'pink', isFrozen: true },
      { id: 'l139-tile-3', color: 'cyan' },
      { id: 'l139-tile-4', color: 'grey' },
      { id: 'l139-tile-5', color: 'grey' },
      { id: 'l139-tile-6', color: 'amber' },
      { id: 'l139-tile-7', color: 'lime', number: 6, allowedColors: ['lime', 'green'] },
      { id: 'l139-tile-8', color: 'amber' },
      { id: 'l139-tile-9', color: 'grey' },
      { id: 'l139-tile-10', color: 'orange' },
      { id: 'l139-tile-11', color: 'grey' },
      { id: 'l139-tile-12', color: 'joker', isJoker: true },
      { id: 'l139-tile-13', color: 'lime', isFrozen: true },
      { id: 'l139-tile-14', color: 'green' },
      { id: 'l139-tile-15', color: 'grey' },
      { id: 'l139-tile-16', color: 'cyan', isFrozen: true },
      { id: 'l139-tile-17', color: 'grey' },
      { id: 'l139-tile-18', color: 'pink' },
      { id: 'l139-tile-19', color: 'green', isFrozen: true },
      { id: 'l139-tile-20', color: 'grey' },
      { id: 'l139-tile-21', color: 'grey' },
      { id: 'l139-tile-22', color: 'purple' },
      { id: 'l139-tile-23', color: 'grey' },
      { id: 'l139-tile-24', color: 'grey' },
      { id: 'l139-tile-25', color: 'purple', number: 4 },
      { id: 'l139-tile-26', color: 'grey' },
      { id: 'l139-tile-27', color: 'lime' },
      { id: 'l139-tile-28', color: 'joker', isJoker: true },
      { id: 'l139-tile-29', color: 'grey' },
      { id: 'l139-tile-30', color: 'grey' },
      { id: 'l139-tile-31', color: 'grey' },
      { id: 'l139-tile-32', color: 'pink' },
      { id: 'l139-tile-33', color: 'pink', isFrozen: true },
      { id: 'l139-tile-34', color: 'grey' },
      { id: 'l139-tile-35', color: 'grey' },
      { id: 'l139-tile-36', color: 'grey' },
      { id: 'l139-tile-37', color: 'grey' },
      { id: 'l139-tile-38', color: 'grey' },
      { id: 'l139-tile-39', color: 'joker', isJoker: true },
      { id: 'l139-tile-40', color: 'blue' },
      { id: 'l139-tile-41', color: 'purple' },
      { id: 'l139-tile-42', color: 'purple', isFrozen: true },
      { id: 'l139-tile-43', color: 'blue', number: 6, allowedColors: ['blue', 'cyan'] },
      { id: 'l139-tile-44', color: 'grey' },
      { id: 'l139-tile-45', color: 'grey' },
      { id: 'l139-tile-46', color: 'grey' },
      { id: 'l139-tile-47', color: 'blue', isFrozen: true },
      { id: 'l139-tile-48', color: 'orange', isFrozen: true },
      { id: 'l139-tile-49', color: 'pink', number: 5 },
    ],
  },
  {
    id: 140,
    title: 'Level 140',
    gridSize: 7,
    initialTiles: [
      { id: 'l140-tile-1', color: 'purple', number: 6, allowedColors: ['purple', 'pink'] },
      { id: 'l140-tile-2', color: 'grey' },
      { id: 'l140-tile-3', color: 'grey' },
      { id: 'l140-tile-4', color: 'amber' },
      { id: 'l140-tile-5', color: 'pink' },
      { id: 'l140-tile-6', color: 'cyan' },
      { id: 'l140-tile-7', color: 'amber', number: 6, allowedColors: ['amber', 'yellow'] },
      { id: 'l140-tile-8', color: 'grey' },
      { id: 'l140-tile-9', color: 'red', isFrozen: true },
      { id: 'l140-tile-10', color: 'grey' },
      { id: 'l140-tile-11', color: 'amber' },
      { id: 'l140-tile-12', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l140-tile-13', color: 'grey' },
      { id: 'l140-tile-14', color: 'grey' },
      { id: 'l140-tile-15', color: 'grey' },
      { id: 'l140-tile-16', color: 'grey' },
      { id: 'l140-tile-17', color: 'indigo' },
      { id: 'l140-tile-18', color: 'red', isFrozen: true },
      { id: 'l140-tile-19', color: 'green' },
      { id: 'l140-tile-20', color: 'grey' },
      { id: 'l140-tile-21', color: 'grey' },
      { id: 'l140-tile-22', color: 'indigo' },
      { id: 'l140-tile-23', color: 'yellow' },
      { id: 'l140-tile-24', color: 'purple' },
      { id: 'l140-tile-25', color: 'indigo', number: 4 },
      { id: 'l140-tile-26', color: 'yellow' },
      { id: 'l140-tile-27', color: 'grey' },
      { id: 'l140-tile-28', color: 'red', isFrozen: true },
      { id: 'l140-tile-29', color: 'grey' },
      { id: 'l140-tile-30', color: 'pink' },
      { id: 'l140-tile-31', color: 'grey' },
      { id: 'l140-tile-32', color: 'cyan' },
      { id: 'l140-tile-33', color: 'grey' },
      { id: 'l140-tile-34', color: 'purple', isFrozen: true },
      { id: 'l140-tile-35', color: 'grey' },
      { id: 'l140-tile-36', color: 'grey' },
      { id: 'l140-tile-37', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l140-tile-38', color: 'grey' },
      { id: 'l140-tile-39', color: 'grey' },
      { id: 'l140-tile-40', color: 'grey' },
      { id: 'l140-tile-41', color: 'grey' },
      { id: 'l140-tile-42', color: 'indigo' },
      { id: 'l140-tile-43', color: 'green', number: 6, allowedColors: ['green', 'cyan'] },
      { id: 'l140-tile-44', color: 'grey' },
      { id: 'l140-tile-45', color: 'green', isFrozen: true },
      { id: 'l140-tile-46', color: 'red' },
      { id: 'l140-tile-47', color: 'grey' },
      { id: 'l140-tile-48', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l140-tile-49', color: 'red', number: 5 },
    ],
  },
  {
    id: 141,
    title: 'Level 141',
    gridSize: 7,
    initialTiles: [
      { id: 'l141-tile-1', color: 'indigo', number: 6, allowedColors: ['indigo', 'blue'] },
      { id: 'l141-tile-2', color: 'grey' },
      { id: 'l141-tile-3', color: 'grey' },
      { id: 'l141-tile-4', color: 'grey' },
      { id: 'l141-tile-5', color: 'yellow' },
      { id: 'l141-tile-6', color: 'grey' },
      { id: 'l141-tile-7', color: 'cyan', number: 6, allowedColors: ['cyan', 'lime'] },
      { id: 'l141-tile-8', color: 'charcoal' },
      { id: 'l141-tile-9', color: 'indigo' },
      { id: 'l141-tile-10', color: 'grey' },
      { id: 'l141-tile-11', color: 'grey' },
      { id: 'l141-tile-12', color: 'grey' },
      { id: 'l141-tile-13', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l141-tile-14', color: 'grey' },
      { id: 'l141-tile-15', color: 'joker', isJoker: true },
      { id: 'l141-tile-16', color: 'yellow' },
      { id: 'l141-tile-17', color: 'lime' },
      { id: 'l141-tile-18', color: 'red' },
      { id: 'l141-tile-19', color: 'grey' },
      { id: 'l141-tile-20', color: 'grey' },
      { id: 'l141-tile-21', color: 'grey' },
      { id: 'l141-tile-22', color: 'cyan' },
      { id: 'l141-tile-23', color: 'grey' },
      { id: 'l141-tile-24', color: 'lime' },
      { id: 'l141-tile-25', color: 'charcoal', number: 4 },
      { id: 'l141-tile-26', color: 'grey' },
      { id: 'l141-tile-27', color: 'grey' },
      { id: 'l141-tile-28', color: 'blue', isFrozen: true },
      { id: 'l141-tile-29', color: 'orange' },
      { id: 'l141-tile-30', color: 'grey' },
      { id: 'l141-tile-31', color: 'orange', isFrozen: true },
      { id: 'l141-tile-32', color: 'charcoal', isFrozen: true },
      { id: 'l141-tile-33', color: 'grey' },
      { id: 'l141-tile-34', color: 'red', isFrozen: true },
      { id: 'l141-tile-35', color: 'joker', isJoker: true },
      { id: 'l141-tile-36', color: 'grey' },
      { id: 'l141-tile-37', color: 'grey' },
      { id: 'l141-tile-38', color: 'grey' },
      { id: 'l141-tile-39', color: 'blue', isFrozen: true },
      { id: 'l141-tile-40', color: 'indigo' },
      { id: 'l141-tile-41', color: 'grey' },
      { id: 'l141-tile-42', color: 'grey' },
      { id: 'l141-tile-43', color: 'orange', number: 6, allowedColors: ['orange', 'red'] },
      { id: 'l141-tile-44', color: 'yellow' },
      { id: 'l141-tile-45', color: 'grey' },
      { id: 'l141-tile-46', color: 'cyan' },
      { id: 'l141-tile-47', color: 'yellow', isFrozen: true },
      { id: 'l141-tile-48', color: 'charcoal', isFrozen: true },
      { id: 'l141-tile-49', color: 'yellow', number: 5 },
    ],
  },
  {
    id: 142,
    title: 'Level 142',
    gridSize: 7,
    initialTiles: [
      { id: 'l142-tile-1', color: 'lime', number: 6, allowedColors: ['lime', 'green', 'cyan'] },
      { id: 'l142-tile-2', color: 'grey' },
      { id: 'l142-tile-3', color: 'pink', isFrozen: true },
      { id: 'l142-tile-4', color: 'grey' },
      { id: 'l142-tile-5', color: 'grey' },
      { id: 'l142-tile-6', color: 'grey' },
      { id: 'l142-tile-7', color: 'charcoal', number: 6, allowedColors: ['charcoal', 'indigo'] },
      { id: 'l142-tile-8', color: 'amber' },
      { id: 'l142-tile-9', color: 'grey' },
      { id: 'l142-tile-10', color: 'grey' },
      { id: 'l142-tile-11', color: 'cyan' },
      { id: 'l142-tile-12', color: 'grey' },
      { id: 'l142-tile-13', color: 'grey' },
      { id: 'l142-tile-14', color: 'indigo' },
      { id: 'l142-tile-15', color: 'grey' },
      { id: 'l142-tile-16', color: 'lime', isFrozen: true },
      { id: 'l142-tile-17', color: 'lime' },
      { id: 'l142-tile-18', color: 'grey' },
      { id: 'l142-tile-19', color: 'grey' },
      { id: 'l142-tile-20', color: 'purple', isFrozen: true },
      { id: 'l142-tile-21', color: 'blue' },
      { id: 'l142-tile-22', color: 'grey' },
      { id: 'l142-tile-23', color: 'pink' },
      { id: 'l142-tile-24', color: 'amber', isFrozen: true },
      { id: 'l142-tile-25', color: 'amber', number: 4 },
      { id: 'l142-tile-26', color: 'charcoal' },
      { id: 'l142-tile-27', color: 'grey' },
      { id: 'l142-tile-28', color: 'blue' },
      { id: 'l142-tile-29', color: 'charcoal', isFrozen: true },
      { id: 'l142-tile-30', color: 'grey' },
      { id: 'l142-tile-31', color: 'grey' },
      { id: 'l142-tile-32', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l142-tile-33', color: 'green' },
      { id: 'l142-tile-34', color: 'amber' },
      { id: 'l142-tile-35', color: 'grey' },
      { id: 'l142-tile-36', color: 'grey' },
      { id: 'l142-tile-37', color: 'grey' },
      { id: 'l142-tile-38', color: 'grey' },
      { id: 'l142-tile-39', color: 'blue' },
      { id: 'l142-tile-40', color: 'grey' },
      { id: 'l142-tile-41', color: 'joker', isJoker: true },
      { id: 'l142-tile-42', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l142-tile-43', color: 'pink', number: 6, allowedColors: ['pink', 'purple'] },
      { id: 'l142-tile-44', color: 'grey' },
      { id: 'l142-tile-45', color: 'indigo', isFrozen: true },
      { id: 'l142-tile-46', color: 'purple' },
      { id: 'l142-tile-47', color: 'blue' },
      { id: 'l142-tile-48', color: 'grey' },
      { id: 'l142-tile-49', color: 'blue', number: 5 },
    ],
  },
  {
    id: 143,
    title: 'Level 143',
    gridSize: 7,
    initialTiles: [
      { id: 'l143-tile-1', color: 'red', number: 6, allowedColors: ['red', 'orange'] },
      { id: 'l143-tile-2', color: 'grey' },
      { id: 'l143-tile-3', color: 'orange' },
      { id: 'l143-tile-4', color: 'grey' },
      { id: 'l143-tile-5', color: 'yellow' },
      { id: 'l143-tile-6', color: 'joker', isJoker: true },
      { id: 'l143-tile-7', color: 'blue', number: 6, allowedColors: ['blue', 'cyan'] },
      { id: 'l143-tile-8', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l143-tile-9', color: 'purple' },
      { id: 'l143-tile-10', color: 'grey' },
      { id: 'l143-tile-11', color: 'grey' },
      { id: 'l143-tile-12', color: 'charcoal', isFrozen: true },
      { id: 'l143-tile-13', color: 'purple', isFrozen: true },
      { id: 'l143-tile-14', color: 'cyan', isFrozen: true },
      { id: 'l143-tile-15', color: 'grey' },
      { id: 'l143-tile-16', color: 'joker', isJoker: true },
      { id: 'l143-tile-17', color: 'red' },
      { id: 'l143-tile-18', color: 'grey' },
      { id: 'l143-tile-19', color: 'orange' },
      { id: 'l143-tile-20', color: 'blue' },
      { id: 'l143-tile-21', color: 'grey' },
      { id: 'l143-tile-22', color: 'charcoal', number: 3 },
      { id: 'l143-tile-23', color: 'purple', isFrozen: true },
      { id: 'l143-tile-24', color: 'charcoal' },
      { id: 'l143-tile-25', color: 'purple', number: 4 },
      { id: 'l143-tile-26', color: 'grey' },
      { id: 'l143-tile-27', color: 'grey' },
      { id: 'l143-tile-28', color: 'red' },
      { id: 'l143-tile-29', color: 'grey' },
      { id: 'l143-tile-30', color: 'amber' },
      { id: 'l143-tile-31', color: 'amber' },
      { id: 'l143-tile-32', color: 'grey' },
      { id: 'l143-tile-33', color: 'lime' },
      { id: 'l143-tile-34', color: 'yellow' },
      { id: 'l143-tile-35', color: 'lime', isFrozen: true },
      { id: 'l143-tile-36', color: 'green', isFrozen: true },
      { id: 'l143-tile-37', color: 'grey' },
      { id: 'l143-tile-38', color: 'grey' },
      { id: 'l143-tile-39', color: 'green' },
      { id: 'l143-tile-40', color: 'grey' },
      { id: 'l143-tile-41', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l143-tile-42', color: 'grey' },
      { id: 'l143-tile-43', color: 'green', number: 6, allowedColors: ['green', 'lime'] },
      { id: 'l143-tile-44', color: 'grey' },
      { id: 'l143-tile-45', color: 'grey' },
      { id: 'l143-tile-46', color: 'cyan', isFrozen: true },
      { id: 'l143-tile-47', color: 'grey' },
      { id: 'l143-tile-48', color: 'blue' },
      { id: 'l143-tile-49', color: 'amber', number: 6, allowedColors: ['amber', 'yellow'] },
    ],
  },
  {
    id: 144,
    title: 'Level 144',
    gridSize: 7,
    initialTiles: [
      { id: 'l144-tile-1', color: 'orange', number: 6, allowedColors: ['orange', 'amber'] },
      { id: 'l144-tile-2', color: 'orange', isFrozen: true },
      { id: 'l144-tile-3', color: 'grey' },
      { id: 'l144-tile-4', color: 'yellow', number: 3 },
      { id: 'l144-tile-5', color: 'charcoal', isFrozen: true },
      { id: 'l144-tile-6', color: 'grey' },
      { id: 'l144-tile-7', color: 'indigo', number: 6, allowedColors: ['indigo', 'blue'] },
      { id: 'l144-tile-8', color: 'grey' },
      { id: 'l144-tile-9', color: 'lime' },
      { id: 'l144-tile-10', color: 'blue' },
      { id: 'l144-tile-11', color: 'amber' },
      { id: 'l144-tile-12', color: 'grey' },
      { id: 'l144-tile-13', color: 'pink' },
      { id: 'l144-tile-14', color: 'orange', isFrozen: true },
      { id: 'l144-tile-15', color: 'grey' },
      { id: 'l144-tile-16', color: 'grey' },
      { id: 'l144-tile-17', color: 'grey' },
      { id: 'l144-tile-18', color: 'grey' },
      { id: 'l144-tile-19', color: 'amber' },
      { id: 'l144-tile-20', color: 'grey' },
      { id: 'l144-tile-21', color: 'grey' },
      { id: 'l144-tile-22', color: 'pink', isFrozen: true },
      { id: 'l144-tile-23', color: 'charcoal' },
      { id: 'l144-tile-24', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l144-tile-25', color: 'pink', number: 4 },
      { id: 'l144-tile-26', color: 'charcoal' },
      { id: 'l144-tile-27', color: 'grey' },
      { id: 'l144-tile-28', color: 'cyan', isFrozen: true },
      { id: 'l144-tile-29', color: 'pink', isFrozen: true },
      { id: 'l144-tile-30', color: 'indigo' },
      { id: 'l144-tile-31', color: 'grey' },
      { id: 'l144-tile-32', color: 'joker', isJoker: true },
      { id: 'l144-tile-33', color: 'grey' },
      { id: 'l144-tile-34', color: 'grey' },
      { id: 'l144-tile-35', color: 'yellow' },
      { id: 'l144-tile-36', color: 'grey' },
      { id: 'l144-tile-37', color: 'cyan' },
      { id: 'l144-tile-38', color: 'yellow' },
      { id: 'l144-tile-39', color: 'indigo' },
      { id: 'l144-tile-40', color: 'lime', isFrozen: true },
      { id: 'l144-tile-41', color: 'grey' },
      { id: 'l144-tile-42', color: 'charcoal' },
      { id: 'l144-tile-43', color: 'lime', number: 6, allowedColors: ['lime', 'cyan'] },
      { id: 'l144-tile-44', color: 'charcoal' },
      { id: 'l144-tile-45', color: 'grey' },
      { id: 'l144-tile-46', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l144-tile-47', color: 'grey' },
      { id: 'l144-tile-48', color: 'blue' },
      { id: 'l144-tile-49', color: 'charcoal', number: 6 },
    ],
  },
  {
    id: 145,
    title: 'Level 145',
    gridSize: 7,
    initialTiles: [
      { id: 'l145-tile-1', color: 'cyan', number: 6, allowedColors: ['cyan', 'blue'] },
      { id: 'l145-tile-2', color: 'grey' },
      { id: 'l145-tile-3', color: 'grey' },
      { id: 'l145-tile-4', color: 'blue', isFrozen: true },
      { id: 'l145-tile-5', color: 'grey' },
      { id: 'l145-tile-6', color: 'grey' },
      { id: 'l145-tile-7', color: 'purple', number: 6, allowedColors: ['purple', 'pink'] },
      { id: 'l145-tile-8', color: 'lime' },
      { id: 'l145-tile-9', color: 'grey' },
      { id: 'l145-tile-10', color: 'grey' },
      { id: 'l145-tile-11', color: 'green' },
      { id: 'l145-tile-12', color: 'joker', isJoker: true },
      { id: 'l145-tile-13', color: 'grey' },
      { id: 'l145-tile-14', color: 'grey' },
      { id: 'l145-tile-15', color: 'red' },
      { id: 'l145-tile-16', color: 'amber' },
      { id: 'l145-tile-17', color: 'purple', isFrozen: true },
      { id: 'l145-tile-18', color: 'lime', isFrozen: true },
      { id: 'l145-tile-19', color: 'grey' },
      { id: 'l145-tile-20', color: 'grey' },
      { id: 'l145-tile-21', color: 'grey' },
      { id: 'l145-tile-22', color: 'green' },
      { id: 'l145-tile-23', color: 'blue' },
      { id: 'l145-tile-24', color: 'grey' },
      { id: 'l145-tile-25', color: 'red', number: 4 },
      { id: 'l145-tile-26', color: 'grey' },
      { id: 'l145-tile-27', color: 'purple', isFrozen: true },
      { id: 'l145-tile-28', color: 'grey' },
      { id: 'l145-tile-29', color: 'blue', isFrozen: true },
      { id: 'l145-tile-30', color: 'cyan' },
      { id: 'l145-tile-31', color: 'red' },
      { id: 'l145-tile-32', color: 'grey' },
      { id: 'l145-tile-33', color: 'grey' },
      { id: 'l145-tile-34', color: 'orange', isFrozen: true },
      { id: 'l145-tile-35', color: 'joker', isJoker: true },
      { id: 'l145-tile-36', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l145-tile-37', color: 'cyan', isFrozen: true },
      { id: 'l145-tile-38', color: 'amber' },
      { id: 'l145-tile-39', color: 'pink' },
      { id: 'l145-tile-40', color: 'orange' },
      { id: 'l145-tile-41', color: 'joker', isJoker: true },
      { id: 'l145-tile-42', color: 'grey' },
      { id: 'l145-tile-43', color: 'amber', number: 6, allowedColors: ['amber', 'orange'] },
      { id: 'l145-tile-44', color: 'red', isFrozen: true },
      { id: 'l145-tile-45', color: 'pink' },
      { id: 'l145-tile-46', color: 'blue', number: 3 },
      { id: 'l145-tile-47', color: 'blue' },
      { id: 'l145-tile-48', color: 'grey' },
      { id: 'l145-tile-49', color: 'green', number: 6, allowedColors: ['green', 'lime'] },
    ],
  },
  {
    id: 146,
    title: 'Level 146',
    gridSize: 7,
    initialTiles: [
      { id: 'l146-tile-1', color: 'pink', number: 6, allowedColors: ['pink', 'purple'] },
      { id: 'l146-tile-2', color: 'pink' },
      { id: 'l146-tile-3', color: 'red', isFrozen: true },
      { id: 'l146-tile-4', color: 'grey' },
      { id: 'l146-tile-5', color: 'indigo' },
      { id: 'l146-tile-6', color: 'grey' },
      { id: 'l146-tile-7', color: 'yellow', number: 6 },
      { id: 'l146-tile-8', color: 'charcoal', isFrozen: true },
      { id: 'l146-tile-9', color: 'grey' },
      { id: 'l146-tile-10', color: 'red', isFrozen: true },
      { id: 'l146-tile-11', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l146-tile-12', color: 'yellow' },
      { id: 'l146-tile-13', color: 'lime' },
      { id: 'l146-tile-14', color: 'lime' },
      { id: 'l146-tile-15', color: 'yellow' },
      { id: 'l146-tile-16', color: 'grey' },
      { id: 'l146-tile-17', color: 'grey' },
      { id: 'l146-tile-18', color: 'grey' },
      { id: 'l146-tile-19', color: 'purple', isFrozen: true },
      { id: 'l146-tile-20', color: 'grey' },
      { id: 'l146-tile-21', color: 'joker', isJoker: true },
      { id: 'l146-tile-22', color: 'blue' },
      { id: 'l146-tile-23', color: 'yellow' },
      { id: 'l146-tile-24', color: 'purple' },
      { id: 'l146-tile-25', color: 'lime', number: 4 },
      { id: 'l146-tile-26', color: 'yellow' },
      { id: 'l146-tile-27', color: 'grey' },
      { id: 'l146-tile-28', color: 'charcoal', number: 3 },
      { id: 'l146-tile-29', color: 'grey' },
      { id: 'l146-tile-30', color: 'grey' },
      { id: 'l146-tile-31', color: 'grey' },
      { id: 'l146-tile-32', color: 'grey' },
      { id: 'l146-tile-33', color: 'orange', isFrozen: true },
      { id: 'l146-tile-34', color: 'grey' },
      { id: 'l146-tile-35', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l146-tile-36', color: 'grey' },
      { id: 'l146-tile-37', color: 'lime', isFrozen: true },
      { id: 'l146-tile-38', color: 'blue' },
      { id: 'l146-tile-39', color: 'grey' },
      { id: 'l146-tile-40', color: 'charcoal', isFrozen: true },
      { id: 'l146-tile-41', color: 'grey' },
      { id: 'l146-tile-42', color: 'grey' },
      { id: 'l146-tile-43', color: 'indigo', number: 6, allowedColors: ['indigo', 'blue'] },
      { id: 'l146-tile-44', color: 'indigo' },
      { id: 'l146-tile-45', color: 'yellow' },
      { id: 'l146-tile-46', color: 'pink' },
      { id: 'l146-tile-47', color: 'grey' },
      { id: 'l146-tile-48', color: 'orange' },
      { id: 'l146-tile-49', color: 'orange', number: 6, allowedColors: ['orange', 'red'] },
    ],
  },
  {
    id: 147,
    title: 'Level 147',
    gridSize: 7,
    initialTiles: [
      { id: 'l147-tile-1', color: 'red', number: 6, allowedColors: ['red', 'orange'] },
      { id: 'l147-tile-2', color: 'grey' },
      { id: 'l147-tile-3', color: 'amber' },
      { id: 'l147-tile-4', color: 'grey' },
      { id: 'l147-tile-5', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l147-tile-6', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l147-tile-7', color: 'blue', number: 6, allowedColors: ['blue', 'cyan'] },
      { id: 'l147-tile-8', color: 'purple' },
      { id: 'l147-tile-9', color: 'green', isFrozen: true },
      { id: 'l147-tile-10', color: 'joker', isJoker: true },
      { id: 'l147-tile-11', color: 'cyan' },
      { id: 'l147-tile-12', color: 'lime' },
      { id: 'l147-tile-13', color: 'red' },
      { id: 'l147-tile-14', color: 'grey' },
      { id: 'l147-tile-15', color: 'grey' },
      { id: 'l147-tile-16', color: 'yellow', isFrozen: true },
      { id: 'l147-tile-17', color: 'cyan', isFrozen: true },
      { id: 'l147-tile-18', color: 'purple', number: 4 },
      { id: 'l147-tile-19', color: 'grey' },
      { id: 'l147-tile-20', color: 'grey' },
      { id: 'l147-tile-21', color: 'grey' },
      { id: 'l147-tile-22', color: 'grey' },
      { id: 'l147-tile-23', color: 'orange' },
      { id: 'l147-tile-24', color: 'grey' },
      { id: 'l147-tile-25', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l147-tile-26', color: 'blue', isFrozen: true },
      { id: 'l147-tile-27', color: 'amber' },
      { id: 'l147-tile-28', color: 'purple' },
      { id: 'l147-tile-29', color: 'cyan' },
      { id: 'l147-tile-30', color: 'purple' },
      { id: 'l147-tile-31', color: 'yellow', isFrozen: true },
      { id: 'l147-tile-32', color: 'cyan', number: 4 },
      { id: 'l147-tile-33', color: 'cyan' },
      { id: 'l147-tile-34', color: 'green', isFrozen: true },
      { id: 'l147-tile-35', color: 'grey' },
      { id: 'l147-tile-36', color: 'grey' },
      { id: 'l147-tile-37', color: 'lime' },
      { id: 'l147-tile-38', color: 'blue', isFrozen: true },
      { id: 'l147-tile-39', color: 'orange' },
      { id: 'l147-tile-40', color: 'cyan' },
      { id: 'l147-tile-41', color: 'grey' },
      { id: 'l147-tile-42', color: 'grey' },
      { id: 'l147-tile-43', color: 'green', number: 6, allowedColors: ['green', 'lime'] },
      { id: 'l147-tile-44', color: 'red' },
      { id: 'l147-tile-45', color: 'grey' },
      { id: 'l147-tile-46', color: 'grey' },
      { id: 'l147-tile-47', color: 'grey' },
      { id: 'l147-tile-48', color: 'grey' },
      { id: 'l147-tile-49', color: 'amber', number: 6, allowedColors: ['amber', 'yellow'] },
    ],
  },
  {
    id: 148,
    title: 'Level 148',
    gridSize: 7,
    initialTiles: [
      { id: 'l148-tile-1', color: 'lime', number: 6, allowedColors: ['lime', 'green'] },
      { id: 'l148-tile-2', color: 'amber' },
      { id: 'l148-tile-3', color: 'blue' },
      { id: 'l148-tile-4', color: 'charcoal', isFrozen: true },
      { id: 'l148-tile-5', color: 'grey' },
      { id: 'l148-tile-6', color: 'pink' },
      { id: 'l148-tile-7', color: 'indigo', number: 6, allowedColors: ['indigo', 'blue'] },
      { id: 'l148-tile-8', color: 'grey' },
      { id: 'l148-tile-9', color: 'grey' },
      { id: 'l148-tile-10', color: 'grey' },
      { id: 'l148-tile-11', color: 'green', isFrozen: true },
      { id: 'l148-tile-12', color: 'grey' },
      { id: 'l148-tile-13', color: 'charcoal' },
      { id: 'l148-tile-14', color: 'indigo', isFrozen: true },
      { id: 'l148-tile-15', color: 'indigo' },
      { id: 'l148-tile-16', color: 'joker', isJoker: true },
      { id: 'l148-tile-17', color: 'grey' },
      { id: 'l148-tile-18', color: 'pink', number: 4 },
      { id: 'l148-tile-19', color: 'grey' },
      { id: 'l148-tile-20', color: 'grey' },
      { id: 'l148-tile-21', color: 'grey' },
      { id: 'l148-tile-22', color: 'grey' },
      { id: 'l148-tile-23', color: 'yellow', isFrozen: true },
      { id: 'l148-tile-24', color: 'grey' },
      { id: 'l148-tile-25', color: 'joker', isJoker: true },
      { id: 'l148-tile-26', color: 'pink', isFrozen: true },
      { id: 'l148-tile-27', color: 'green' },
      { id: 'l148-tile-28', color: 'grey' },
      { id: 'l148-tile-29', color: 'charcoal' },
      { id: 'l148-tile-30', color: 'grey' },
      { id: 'l148-tile-31', color: 'lime' },
      { id: 'l148-tile-32', color: 'yellow', number: 4 },
      { id: 'l148-tile-33', color: 'yellow' },
      { id: 'l148-tile-34', color: 'charcoal' },
      { id: 'l148-tile-35', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l148-tile-36', color: 'amber' },
      { id: 'l148-tile-37', color: 'grey' },
      { id: 'l148-tile-38', color: 'grey' },
      { id: 'l148-tile-39', color: 'yellow', isFrozen: true },
      { id: 'l148-tile-40', color: 'blue' },
      { id: 'l148-tile-41', color: 'orange' },
      { id: 'l148-tile-42', color: 'grey' },
      { id: 'l148-tile-43', color: 'orange', number: 6, allowedColors: ['orange', 'amber'] },
      { id: 'l148-tile-44', color: 'orange', isFrozen: true },
      { id: 'l148-tile-45', color: 'grey' },
      { id: 'l148-tile-46', color: 'lime' },
      { id: 'l148-tile-47', color: 'charcoal', isFrozen: true },
      { id: 'l148-tile-48', color: 'pink', isFrozen: true },
      { id: 'l148-tile-49', color: 'charcoal', number: 6 },
    ],
  },
  {
    id: 149,
    title: 'Level 149',
    gridSize: 7,
    initialTiles: [
      { id: 'l149-tile-1', color: 'cyan', number: 7, allowedColors: ['cyan', 'blue', 'green'] },
      { id: 'l149-tile-2', color: 'grey' },
      { id: 'l149-tile-3', color: 'grey' },
      { id: 'l149-tile-4', color: 'grey' },
      { id: 'l149-tile-5', color: 'red', isFrozen: true },
      { id: 'l149-tile-6', color: 'orange', isFrozen: true },
      { id: 'l149-tile-7', color: 'amber', number: 7, allowedColors: ['amber', 'yellow', 'orange'] },
      { id: 'l149-tile-8', color: 'indigo' },
      { id: 'l149-tile-9', color: 'purple' },
      { id: 'l149-tile-10', color: 'joker', isJoker: true },
      { id: 'l149-tile-11', color: 'joker', isJoker: true },
      { id: 'l149-tile-12', color: 'joker', isJoker: true },
      { id: 'l149-tile-13', color: 'grey' },
      { id: 'l149-tile-14', color: 'grey' },
      { id: 'l149-tile-15', color: 'grey' },
      { id: 'l149-tile-16', color: 'grey' },
      { id: 'l149-tile-17', color: 'grey' },
      { id: 'l149-tile-18', color: 'blue', isFrozen: true },
      { id: 'l149-tile-19', color: 'pink', isFrozen: true },
      { id: 'l149-tile-20', color: 'indigo', isFrozen: true },
      { id: 'l149-tile-21', color: 'grey' },
      { id: 'l149-tile-22', color: 'grey' },
      { id: 'l149-tile-23', color: 'lime', number: 3 },
      { id: 'l149-tile-24', color: 'purple', isFrozen: true },
      { id: 'l149-tile-25', color: 'grey' },
      { id: 'l149-tile-26', color: 'joker', isJoker: true },
      { id: 'l149-tile-27', color: 'charcoal', number: 3 },
      { id: 'l149-tile-28', color: 'grey' },
      { id: 'l149-tile-29', color: 'grey' },
      { id: 'l149-tile-30', color: 'grey' },
      { id: 'l149-tile-31', color: 'lime' },
      { id: 'l149-tile-32', color: 'lime' },
      { id: 'l149-tile-33', color: 'charcoal' },
      { id: 'l149-tile-34', color: 'orange', isFrozen: true },
      { id: 'l149-tile-35', color: 'charcoal' },
      { id: 'l149-tile-36', color: 'blue' },
      { id: 'l149-tile-37', color: 'amber' },
      { id: 'l149-tile-38', color: 'yellow' },
      { id: 'l149-tile-39', color: 'yellow', isFrozen: true },
      { id: 'l149-tile-40', color: 'cyan', isFrozen: true },
      { id: 'l149-tile-41', color: 'grey' },
      { id: 'l149-tile-42', color: 'red' },
      { id: 'l149-tile-43', color: 'purple', number: 7, allowedColors: ['purple', 'indigo', 'pink'] },
      { id: 'l149-tile-44', color: 'green' },
      { id: 'l149-tile-45', color: 'amber' },
      { id: 'l149-tile-46', color: 'orange', isFrozen: true },
      { id: 'l149-tile-47', color: 'pink' },
      { id: 'l149-tile-48', color: 'cyan' },
      { id: 'l149-tile-49', color: 'red', number: 7, allowedColors: ['red', 'orange', 'pink'] },
    ],
  },
  {
    id: 150,
    title: 'Level 150',
    gridSize: 7,
    initialTiles: [
      { id: 'l150-tile-1', color: 'indigo', number: 7, allowedColors: ['indigo', 'blue', 'purple'] },
      { id: 'l150-tile-2', color: 'grey' },
      { id: 'l150-tile-3', color: 'purple', isFrozen: true },
      { id: 'l150-tile-4', color: 'amber' },
      { id: 'l150-tile-5', color: 'grey' },
      { id: 'l150-tile-6', color: 'grey' },
      { id: 'l150-tile-7', color: 'green', number: 7, allowedColors: ['green', 'lime', 'cyan'] },
      { id: 'l150-tile-8', color: 'cyan' },
      { id: 'l150-tile-9', color: 'charcoal', isFrozen: true },
      { id: 'l150-tile-10', color: 'purple', isFrozen: true },
      { id: 'l150-tile-11', color: 'amber', isFrozen: true },
      { id: 'l150-tile-12', color: 'indigo', isFrozen: true },
      { id: 'l150-tile-13', color: 'grey' },
      { id: 'l150-tile-14', color: 'yellow', isFrozen: true },
      { id: 'l150-tile-15', color: 'yellow' },
      { id: 'l150-tile-16', color: 'green' },
      { id: 'l150-tile-17', color: 'grey' },
      { id: 'l150-tile-18', color: 'yellow', number: 4 },
      { id: 'l150-tile-19', color: 'joker', isJoker: true },
      { id: 'l150-tile-20', color: 'lime', isFrozen: true },
      { id: 'l150-tile-21', color: 'joker', isJoker: true },
      { id: 'l150-tile-22', color: 'orange' },
      { id: 'l150-tile-23', color: 'orange', isFrozen: true },
      { id: 'l150-tile-24', color: 'grey' },
      { id: 'l150-tile-25', color: 'red' },
      { id: 'l150-tile-26', color: 'joker', isJoker: true, isFrozen: true },
      { id: 'l150-tile-27', color: 'grey' },
      { id: 'l150-tile-28', color: 'grey' },
      { id: 'l150-tile-29', color: 'grey' },
      { id: 'l150-tile-30', color: 'pink' },
      { id: 'l150-tile-31', color: 'joker', isJoker: true },
      { id: 'l150-tile-32', color: 'charcoal', number: 4 },
      { id: 'l150-tile-33', color: 'green' },
      { id: 'l150-tile-34', color: 'pink', isFrozen: true },
      { id: 'l150-tile-35', color: 'charcoal', isFrozen: true },
      { id: 'l150-tile-36', color: 'red' },
      { id: 'l150-tile-37', color: 'yellow' },
      { id: 'l150-tile-38', color: 'lime' },
      { id: 'l150-tile-39', color: 'grey' },
      { id: 'l150-tile-40', color: 'charcoal', isFrozen: true },
      { id: 'l150-tile-41', color: 'blue' },
      { id: 'l150-tile-42', color: 'blue' },
      { id: 'l150-tile-43', color: 'orange', number: 7, allowedColors: ['orange', 'amber', 'red'] },
      { id: 'l150-tile-44', color: 'indigo' },
      { id: 'l150-tile-45', color: 'grey' },
      { id: 'l150-tile-46', color: 'grey' },
      { id: 'l150-tile-47', color: 'purple' },
      { id: 'l150-tile-48', color: 'grey' },
      { id: 'l150-tile-49', color: 'pink', number: 7, allowedColors: ['pink', 'purple', 'red'] },
    ],
  },
];

export const LEVEL_MAX_MOVES_111_150: Record<number, number> = {
  111: 18,
  112: 22,
  113: 24,
  114: 26,
  115: 30,
  116: 32,
  117: 34,
  118: 36,
  119: 36,
  120: 38,
  121: 38,
  122: 40,
  123: 42,
  124: 42,
  125: 44,
  126: 42,
  127: 44,
  128: 44,
  129: 46,
  130: 46,
  131: 46,
  132: 48,
  133: 48,
  134: 48,
  135: 50,
  136: 52,
  137: 52,
  138: 54,
  139: 54,
  140: 54,
  141: 54,
  142: 56,
  143: 56,
  144: 56,
  145: 58,
  146: 58,
  147: 58,
  148: 58,
  149: 60,
  150: 60,
};
